- .travis.yml
- build.gradle
https://tools.hmcts.net/jira/browse/RDM-1949
Addition of Travis CI configuration file.
```
[ ] Yes
[X] No
```
> RDM-1949: Addition of Travis CI configuration

- src/test/java/uk/gov/hmcts/ccd/domain/service/search/CreatorSearchOperationTest.java
> Attempt to fix build.

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/variables.tf
N/A
Use product/component name as defined in `Jenkinsfile`.
```
[ ] Yes
[x] No
```
> CNP: Fix product/component name

- infrastructure/main.tf
N/A
Revert DB name to `data-store` to prevent recreation of DB.
```
[ ] Yes
[x] No
```
> Revert DB name

- infrastructure/aat.tfvars
N/A
Use preprod config for AAT.
```
[ ] Yes
[x] No
```
> CNP: Add AAT config for tactical preprod

- build.gradle
- dependency-check-suppressions.xml
RDM-2012
Added `dependencyCheck` for the new pipeline
```
[x] Yes
[ ] No
```
> RDM-2012 Added dependency Check for the new pipeline

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/RDM-1961
Update valid DM domain regex to include existing tactical OR new CNP domain for DM.
```
[ ] Yes
[x] No
```
> Validate DM domains against legacy (tactical) and CNP

- dependency-check-suppressions.xml
N/A
Temporarily suppress dependency vulnerability CVE-2018-1199
```
[ ] Yes
[x] No
```
> Suppress CVE-2018-1199

- dependency-check-suppressions.xml
N/A
Temporarily suppress Apache Tomcat CVE
```
[ ] Yes
[x] No
```
> Suppress Apache Tomcat CVE

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/prod.tfvars
N/A
Support HTTP URIs for documents
```
[ ] Yes
[x] No
```
> Allow HTTP for document URIs

- infrastructure/main.tf
- infrastructure/variables.tf
Sandbox configuration change for probate team
```
[x] Yes
[ ] No
```
> Sandbox configuration change for probate team

- src/main/java/uk/gov/hmcts/ccd/domain/types/sanitiser/client/DocumentManagementRestClient.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/sanitiser/client/DocumentManagementRestClientTest.java
N/A
Enable S2S for DM integration
```
[ ] Yes
[x] No
```
> Enable S2S for DM integration

- src/main/java/uk/gov/hmcts/ccd/data/SecurityUtils.java
- src/test/java/uk/gov/hmcts/ccd/data/SecurityUtilsTest.java
N/A
Add `user-id` and `user-roles` for DM integration
```
[ ] Yes
[x] No
```
> Add `user-id` and `user-roles` for DM integration

- infrastructure/main.tf
n / a
Fix default default print url.  It was not copied and pasted correctly
```
[x] Yes
[ ] No
```
> Fix default default print url

- dependency-check-suppressions.xml
N/A
Suppress CVE-2018-1196 as this is not applicable to the current project.
```
[ ] Yes
[x] No
```
> Suppress CVE-2018-1196

- README.md
- src/main/java/uk/gov/hmcts/ccd/RestTemplateConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/hmcts/ccd/WireMockBaseTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/UserProfileEndpointTest.java
RDM-2043
Add Pooling Connection Manager
```
[x] Yes
[ ] No
```
> RDM 2043 Pooling Connection manager

- src/main/java/uk/gov/hmcts/ccd/RestTemplateConfiguration.java
- src/test/java/uk/gov/hmcts/ccd/WireMockBaseTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/UserProfileEndpointTest.java
> Revert test code

- src/test/java/uk/gov/hmcts/ccd/RestTemplateConfigurationTest.java
RDM-2043
```
[ ] Yes
[ ] No
```
> RDM-2043 Add config test case to show that restTemplate can be used

- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetails.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetailsTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetCaseViewOperationTest.java
Fixed bug with Label field type now being displayed on case view tab sections
https://tools.hmcts.net/jira/browse/RDM-2069
```
[ ] Yes
[ ] No
```
> Rdm 2069_off_demo

- src/test/java/uk/gov/hmcts/ccd/RestTemplateConfigurationTest.java
> Fix a broken build

- Dockerfile
- docker-compose.yml
- hub.Dockerfile
RDM-2049
Enable docker image build
```
[x] Yes
[ ] No
```
> RDM-2049 Enable docker image build

- infrastructure/main.tf
- infrastructure/sandbox.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2173
Create a new empty DB in UK South location with a switch turned off by default.
The switch has been turned on for sandbox and the migration tested.
```
[ ] Yes
[x] No
```
> Add Postgres UK DB

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- infrastructure/main.tf
- infrastructure/outputs.tf
Only deploy to saat or sprod, nayab was accidentally deploying to sandbox before
```
[ ] Yes
[ ] No
```
> Remove unneeded options

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/MetaData.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/SearchQueryFactoryOperation.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpoint.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpoint.java
- src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/SQLBuilderForSearchTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointTest.java
https://tools.hmcts.net/jira/browse/ROC-3537
Added metadata parameter sortDirection, which accepts 'asc' or 'desc' (ignoring case)
```
[ ] Yes
[x] No
```
> ROC-3537 Make sort direction configurable

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseAuditEventEntity.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewEvent.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/std/AuditEvent.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetEventTriggerOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/GetEventTriggerOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/callbacks/EventTokenService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/SubmitCaseTransaction.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/DefaultCreateEventOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/ClassifiedStartEventOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/DefaultStartEventOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/StartEventOperation.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpoint.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpoint.java
- src/main/resources/db/changelog/db.changelog-RDM-2209.xml
- src/main/resources/db/changelog/db.changelog-master.xml
- src/test/java/uk/gov/hmcts/ccd/BaseTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetEventTriggerOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/GetEventTriggerOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/createcase/SubmitCaseTransactionTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/ClassifiedStartEventOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CallbackTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
https://tools.hmcts.net/jira/browse/RDM-2209
Prepare migration to strategic IDAM by converting user ID to string.
```
[ ] Yes
[x] No
```
> RDM-2209: Convert user ID to string

- dependency-check-suppressions.xml
> Add cve exceptions

- Jenkinsfile_parameterized
N/A
:warning: At the moment, deployment of `master` branch to any Sandbox environment using the parameterised pipeline would fail because an env variable is missing.
This ass the missing variable as part of the pipeline.
```
[ ] Yes
[x] No
```
> RDM-2210: Fix Sandbox pipeline

- src/main/java/uk/gov/hmcts/ccd/domain/types/BaseTypeValidator.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/DateValidator.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/EmailValidator.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/FixedListValidator.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/NumberValidator.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/PhoneUKValidator.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/PostCodeValidator.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/TextValidator.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/DateValidatorTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/EmailValidatorTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/FixedListValidatorTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/NumberValidatorTest.java
https://tools.hmcts.net/jira/browse/RDM-1920
Use default message when regular expression validation failed
```
[ ] Yes
[x] No
```
> Use default message when regular expression failed

- .travis.yml
- build.gradle
- dependency-check-suppressions.xml
Update jar version and reduce items in suppress list
```
[ ] Yes
[x] No
```
> [SKIP-PREVIEW] Update jars

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2287
Switch back to using 'master' branch for 'moj-module-postgres'
```
[ ] Yes
[X] No
```
> Switch moj-module-postgres to master

- infrastructure/main.tf
- infrastructure/variables.tf
Fixes: https://tools.hmcts.net/jira/browse/RDM-2387
Implement the pattern outline in https://tools.hmcts.net/confluence/display/CNP/Preview+Environment#PreviewEnvironment-TerraformConfiguration
```
[ ] Yes
[X] No
```
> RDM-2387 moj-module-(postgres|webapp) use common_tags

- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetDraftViewOperation.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseDataServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
fix broken tests etc.
```
[Y] Yes
[ ] No
```
> changes for save and resume to fix demo env

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/MetaData.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/AbstractCaseView.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewField.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewFieldBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetails.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseField.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/SearchResultField.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/search/Field.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/search/SearchResultView.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/search/SearchResultViewColumn.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/search/SearchResultViewItem.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AbstractDefaultGetCaseViewOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultFindSearchInputOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultFindWorkbasketInputOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetCaseViewOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetEventTriggerOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/MergeDataToSearchResultOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/SearchQueryOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlService.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpoint.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpoint.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetailsTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultFindSearchInputOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultFindWorkbasketInputOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetCaseViewOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/MergeDataToSearchResultOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
Reverts hmcts/ccd-data-store-api#126
> Revert "RDM-626 - Display metadata in search results"

- .travis.yml
https://tools.hmcts.net/jira/browse/RDM-2288
Remove sudo, cleanup, use recommended caching 
```
[ ] Yes
[X] No
```
> [SKIP-PREVIEW] Sudoless Travis

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- infrastructure/main.tf
- infrastructure/outputs.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2625
1. Add shared vault/remove local
2. Copy secrets to shared vault
3. Copy extra uncopied secrets
> [PREVIEW] Make use of shared keyvault (Step 2)

- Jenkinsfile_nightly
Enable for security related dependency checking.
https://tools.hmcts.net/jira/browse/RDM-2311
> Enable Jenkins nightly builds

- infrastructure/aat.tfvars
- infrastructure/preview.tfvars
RDM-2723
Point AAT and Preview back to Tactical IDAM
```
[ ] Yes
[x] No
```
> RDM-2723: Revert to Tactical IDAM

- infrastructure/main.tf
Remove keys that we tried to copy into the Azure vault
https://tools.hmcts.net/jira/browse/RDM-2484 step 1
```
[ ] Yes
[X] No
```
> [PREVIEW] RDM-2484 Remove copied keys

- infrastructure/aat.tfvars
- infrastructure/preview.tfvars
Reverts hmcts/ccd-data-store-api#161
> RDM-2723: Switch to SIDAM

- infrastructure/aat.tfvars
- infrastructure/preview.tfvars
Reverts hmcts/ccd-data-store-api#174
> RDM-2723: Switch to back to TIDAM

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2484
Cleanup, adjust names of shared vault, convert strings to use shared
vault not local
Keep local shared vault, cause of the existing key.
```
[ ] Yes
[x] No
```
> [PREVIEW] Use shared vault

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2484
```
[ ] Yes
[x] No
```
> [PREVIEW] Remove local and Hashi vaults

- config/checkstyle/checkstyle.xml
- src/main/java/uk/gov/hmcts/ccd/data/definition/CachedUIDefinitionGateway.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/JurisdictionDisplayProperties.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/getcase/CreatorGetCaseOperationTest.java
https://tools.hmcts.net/jira/browse/RDM-2604
```
[ ] Yes
[x] No
```
> Checkstyle: import checks hard errors

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/sprod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2635
Set aat and prod to use the existing per app ASPs.
```
[ ] Yes
[x] No
```
> [PREVIEW] Shared App Service Plan

- src/main/java/uk/gov/hmcts/ccd/config/JacksonObjectMapperConfig.java
- src/main/java/uk/gov/hmcts/ccd/v2/V2.java
- src/main/java/uk/gov/hmcts/ccd/v2/external/controller/CaseController.java
https://tools.hmcts.net/jira/browse/RDM-2736
Fix quality defects failing Sonar on path to live
```
[ ] Yes
[x] No
```
> RDM-2736: Fix Sonar quality on path to live

- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/RDM-3011
Use DNS `idam-api.platform.hmcts.net` for prod IDAM API
```
[ ] Yes
[x] No
```
> [PREVIEW] RDM-3011: Change IDAM API DNS

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDM-3046
```
[ ] Yes
[x] No
```
> Enable Docker build in CNP pipeline RDM-3046

- src/main/resources/db/changelog/db.changelog-RDM-2839.xml
- src/main/resources/db/changelog/db.changelog-master.xml
https://tools.hmcts.net/jira/browse/RDM-2839
Schema changes only:
* Add `case_role` column to table `case_users`
* Add `case_role` column to table `case_users_audit`
```
[ ] Yes
[x] No
```
> RDM-2839: Add `case_role` columns to DB schema

- Dockerfile
- hub.Dockerfile
https://tools.hmcts.net/jira/browse/RDM-2687
```
[ ] Yes
[x] No
```
> Docker: use cnp-java-base image

- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RPE-657
Add bulk scanning to authorised services
```
[ ] Yes
[x] No
```
> Add bulk scanning to authorised services

- infrastructure/sprod.tfvars
> enable ES on sprod

- infrastructure/demo.tfvars
> enable ES on demo

- src/aat/java/uk/gov/hmcts/ccd/datastore/tests/functional/elasticsearch/ElasticsearchTestDataLoaderExtension.java
https://tools.hmcts.net/jira/browse/RDM-3125
Functional test fix
```
[ ] Yes
[X] No
```
> [PREVIEW] RDM-3125 - enable test when elasticsearch enabled

- dependency-check-suppressions.xml
N/A
Temporarily suppress CVE-2018-10237
```
[ ] Yes
[x] No
```
> Fix for CVE-2018-10237

- infrastructure/aat.tfvars
> enable ES on aat

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- src/aat/java/uk/gov/hmcts/ccd/datastore/tests/AATHelper.java
- src/aat/java/uk/gov/hmcts/ccd/datastore/tests/functional/elasticsearch/ElasticsearchBaseTest.java
N/A
add environment variables required for Elasticsearch functional test on AAT
```
[ ] Yes
[x] No
```
> [PREVIEW] Enable ES functional test on AAT

- infrastructure/main.tf
- infrastructure/outputs.tf
- infrastructure/variables.tf
- src/aat/java/uk/gov/hmcts/ccd/datastore/tests/helper/elastic/ElasticsearchHelper.java
N/A
Attempt to enable ES functional test on AAT
```
[ ] Yes
[x] No
```
> Attempt to enable ES functional test on AAT

- infrastructure/main.tf
- infrastructure/outputs.tf
N/A
Added missing DEFINITION_STORE_HOST to ouputs.tf
```
[ ] Yes
[x] No
```
> Enable ES functional tests - define missing env variable in outputs

- infrastructure/aat.tfvars
> disable ES for AAT

- infrastructure/variables.tf
None
Whitelist FPL Case Service
```
[ ] Yes
[x] No
```
> Whitelist FPL Case Service

- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewField.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewFieldBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/FieldType.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseDataService.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/CaseDataValidator.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/CollectionValidator.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/sanitiser/CollectionSanitiser.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/sanitiser/ComplexSanitiser.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpoint.java
- src/test/java/uk/gov/hmcts/ccd/data/definition/DefaultCaseDefinitionRepositoryIT.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseDataServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/CollectionValidatorTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/sanitiser/CollectionSanitiserTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/sanitiser/ComplexSanitiserTest.java
Reverts hmcts/ccd-data-store-api#253
> Revert "RDM-2455 CRUD contract on Collection Items - Standard API"

- infrastructure/prod.tfvars
> enable ES on prod

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-2846
```
[ ] Yes
[ ] No
```
> Bump dependency-management from 1.0.5.RELEASE to 1.0.6.RELEASE

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-3592
```
[ ] Yes
[ ] No
```
> Lock AzureRM to v1.19.0

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- infrastructure/main.tf
- infrastructure/outputs.tf
https://tools.hmcts.net/jira/browse/RDM-2931
```
[ ] Yes
[ ] No
```
> [PREVIEW] Use s2s vault

- src/main/java/uk/gov/hmcts/ccd/endpoint/exceptions/ForbiddenException.java
- src/main/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisation.java
- src/main/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/v2/V2.java
- src/main/java/uk/gov/hmcts/ccd/v2/external/controller/CaseController.java
- src/main/java/uk/gov/hmcts/ccd/v2/external/controller/CaseUserController.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationConfigurationTest.java
- src/test/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationTest.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseUserControllerTest.java
RDM-2836
- Add `PUT /cases/{caseId}/users/{userId}` endpoint
- Add swagger doc for endpoint
- Extract API errors into centralised class
```
[ ] Yes
[ ] No
```
> RDM-2836 3/3: Set case roles: Endpoint

- src/main/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperation.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/exceptions/ForbiddenException.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/exceptions/InvalidCaseRoleException.java
- src/main/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisation.java
- src/main/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/v2/V2.java
- src/main/java/uk/gov/hmcts/ccd/v2/external/controller/CaseController.java
- src/main/java/uk/gov/hmcts/ccd/v2/external/controller/CaseUserController.java
- src/main/java/uk/gov/hmcts/ccd/v2/external/domain/CaseUser.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationConfigurationTest.java
- src/test/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationTest.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseUserControllerTest.java
RDM-2836
* Update user accesses by granting and/or revoking roles to match target state
```
[ ] Yes
[x] No
```
> RDM-2836 2/3: Set case roles: Update user access

- src/test/java/uk/gov/hmcts/ccd/RestTemplateConfigurationTest.java
- src/test/java/uk/gov/hmcts/ccd/WireMockBaseTest.java
- src/test/java/uk/gov/hmcts/ccd/data/definition/HttpUIDefinitionGatewayTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/stdapi/DocumentsOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/CaseDataValidatorTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CallbackTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/CallbackTest.java
- src/test/java/uk/gov/hmcts/ccd/integrations/IntegrationTest.java
> Rdm 3119 attempt3

- src/test/java/uk/gov/hmcts/ccd/RestTemplateConfigurationTest.java
- src/test/java/uk/gov/hmcts/ccd/WireMockBaseTest.java
- src/test/java/uk/gov/hmcts/ccd/data/definition/HttpUIDefinitionGatewayTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/stdapi/DocumentsOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/CaseDataValidatorTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CallbackTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/CallbackTest.java
- src/test/java/uk/gov/hmcts/ccd/integrations/IntegrationTest.java
> Rdm 3119 attempt4

- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewField.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewFieldBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseEventField.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseTypeTabField.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewFieldBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
Frontend to consume JSON from data store
https://tools.hmcts.net/jira/browse/RDM-3530
Make changes to domain objects in the data store so that its rendered on the frontend
```
[ ] Yes
[X] No
```
> First cut of displaycontextparameter column changes

- src/test/java/uk/gov/hmcts/ccd/RestTemplateConfigurationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/stdapi/DocumentsOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/integrations/IntegrationTest.java
> Fix Flaky Data Store Build additional changes

- infrastructure/variables.tf
Added IAC as an authorised service.
```
[ ] Yes
[x] No
```
> Updating authorised services

- infrastructure/demo.tfvars
https://tools.hmcts.net/jira/browse/RDM-3765
```
[ ] Yes
[ ] No
```
> Use per app ASP on demo

- build.gradle
> allow running tests under `v2` folder as smoke

- .travis.yml
- README.md
https://tools.hmcts.net/jira/browse/RDM-3793
```
[ ] Yes
[ ] No
```
> Use OpenJDK instead of Oracle

- infrastructure/saat.tfvars
N/A
Disable ES on SAAT
```
[ ] Yes
[x] No
```
> Disable ES on SAAT

- Dockerfile
https://tools.hmcts.net/jira/browse/RDM-3745
```
[ ] Yes
[ ] No
```
> Upgrade Dockerfile base image

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-3790
```
[ ] Yes
[ ] No
```
> Bump se.patrikerdes.use-latest-versions from 0.2.3 to 0.2.7

- infrastructure/saat.tfvars
RDM-3960
https://tools.hmcts.net/jira/browse/RDM-3960
```
[ ] Yes
[ ] No
```
> Swith to SIDAM for testing

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-3973
```
[ ] Yes
[ ] No
```
> Bump webapp cache to 1400MB

- infrastructure/saat.tfvars
https://tools.hmcts.net/jira/browse/RDM-3960
```
[ ] Yes
[ ] No
```
> Use per app ASP on SAAT

- Dockerfile
- Jenkinsfile_CNP
- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/requirements.lock
- charts/ccd-data-store-api/requirements.yaml
- charts/ccd-data-store-api/values.aat.template.yaml
- charts/ccd-data-store-api/values.template.yaml
https://tools.hmcts.net/jira/browse/RDM-3396
```
[ ] Yes
[ ] No
```
> Enable Helm charts

- src/main/resources/db/changelog/db.changelog-RDM-3922-part-2.xml
- src/main/resources/db/changelog/db.changelog-master.xml
> added JSONB indexes on some fields to fix prod high db cpu issue

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-4064
```
[ ] Yes
[ ] No
```
> Get swagger docs building

- Dockerfile
- hub.Dockerfile
https://tools.hmcts.net/jira/browse/RDM-4058
```
[ ] Yes
[ ] No
```
> Align Dockerfiles

- build.gradle
- src/main/java/uk/gov/hmcts/ccd/config/JacksonObjectMapperConfig.java
- src/main/java/uk/gov/hmcts/ccd/config/JaywayJsonPathConfig.java
- src/main/java/uk/gov/hmcts/ccd/config/JaywayJsonPathConfigHelper.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseField.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseType.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/SearchAliasField.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/DefaultObjectMapperService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/ObjectMapperService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/CrossCaseTypeSearchRequest.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/AuthorisedCaseSearchOperation.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseSearchEndpoint.java
- src/test/java/uk/gov/hmcts/ccd/JsonPathExtension.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/DefaultObjectMapperServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/CrossCaseTypeSearchRequestTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/ElasticsearchCaseSearchOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/AuthorisedCaseSearchOperationTest.java
https://tools.hmcts.net/jira/browse/RDM-3487
Code changes to limit case data in search results to select aliases
```
[ ] Yes
[x] No
```
> RDM-3487 - Cross-case type search: Limit results to select aliases

- infrastructure/main.tf
> Update SKU to 8 core

- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/variables.tf
> Allow DB pool size configuration

- infrastructure/prod.tfvars
Connection timeout: reduce 30s to 10s
Max connections: double to 100->200
Max clients per route: double 20->40
```
[ ] Yes
[ ] No
```
> Tune prod http pool settings

- src/main/resources/db/changelog/db.changelog-RDM-4060-part-1.xml
- src/main/resources/db/changelog/db.changelog-master.xml
https://tools.hmcts.net/jira/browse/RDM-4060
```
[ ] Yes
[ ] No
```
> Add index for {subscriptions,appellantSubscription,tya}

- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/sprod.tfvars
- infrastructure/state.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-4223
```
[ ] Yes
[ ] No
```
> [PREVIEW] Remove Remote Terraform

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/sprod.tfvars
- infrastructure/variables.tf
* SKU name
* Number if cores
* Database disk size
Tested deployment on sprod and all good.
https://tools.hmcts.net/jira/browse/RDM-4242
```
[ ] Yes
[ ] No
```
> Allow scaling of database

- src/main/java/uk/gov/hmcts/ccd/data/definition/HttpUIDefinitionGateway.java
https://tools.hmcts.net/jira/browse/RDM-4211
```
[ ] Yes
[ ] No
```
> Remove unneeded trackDependency

- src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/RDM-4377
```
[ ] Yes
[ ] No
```
> Use standard loglevel for ccd.domain.service

- src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationUtils.java
> Treat empty string as null for security classifications

- Jenkinsfile_CNP
- charts/ccd-data-store-api/values.aat.template.yaml
- charts/ccd-data-store-api/values.template.yaml
- infrastructure/preview.tfvars
switching preview to look at SIDAM
> switching preview to look at SIDAM

- infrastructure/demo.tfvars
> Change idam_api_url to point to SIDAM

- charts/ccd-data-store-api/values.template.yaml
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/sprod.tfvars
- infrastructure/variables.tf
- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/CaseTypeDefinitionVersion.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/DefaultCaseDefinitionRepository.java
- src/main/resources/application.properties
- src/test/java/uk/gov/hmcts/ccd/TestConfiguration.java
- src/test/java/uk/gov/hmcts/ccd/integrations/DefinitionsCachingIT.java
- src/test/resources/integration_tests.properties
> added caching for getVersion and fixed name of the TTL app param

- infrastructure/sprod.tfvars
> Change idam_api_url to SIDAM

- infrastructure/demo.tfvars
Switch Demo to look at AAT SIDAM
> SIDAM idam_api_url

- src/main/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackService.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackServiceTest.java
https://tools.hmcts.net/jira/browse/RDM-3515
This PR fixes the the error message discloses callback URL security issue
```
[ ] Yes
[X] No
```
> RDM-3515 Alter code that discloses the callback url

- infrastructure/saat.tfvars
> SIDAM Switch

- build.gradle
NA
Fix OWASP issue
```
[ ] Yes
[x] No
```
> Fix OWASP issue

- Dockerfile
> fix docker health checker

- charts/ccd-data-store-api/values.yaml
- infrastructure/variables.tf
> add cmc_claim_external_api as trusted s2s service

- infrastructure/variables.tf
- src/main/resources/db/changelog/db.changelog-RDM-4776.xml
- src/main/resources/db/changelog/db.changelog-master.xml
Queries added based on slow running counts in AppInsights.
https://tools.hmcts.net/jira/browse/RDM-4776
```
[ ] Yes
[ ] No
```
> [PREVIEW] Add indexes for slow JSON searches

- src/test/java/uk/gov/hmcts/ccd/data/caseaccess/CaseUserRepositoryTest.java
- src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/SearchQueryFactoryOperationTest.java
- src/test/resources/sql/insert_case_users.sql
**Jira Link:** 
https://tools.hmcts.net/jira/browse/RDM-4797
**Change description**
CaseUserRepositoryTest - test methods have been updated / new test method has been added 
```
[ ] Yes
[X ] No
```
> test: RDM-4797-ccd-am_integration - increase the unit test coverage

- infrastructure/ithc.tfvars
- infrastructure/main.tf
- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
- infrastructure/sprod.tfvars
https://tools.hmcts.net/jira/browse/RDM-4571
```
[ ] Yes
[ ] No
```
> Deploy perftest env

- src/main/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/CaseSearchRequest.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseSearchEndpoint.java
> removed no longer needed INFO logging

- build.gradle
- src/aat/java/uk/gov/hmcts/ccd/datastore/tests/helper/elastic/ElasticsearchTestDataLoaderExtension.java
- src/aat/java/uk/gov/hmcts/ccd/datastore/tests/util/TestUtils.java
https://tools.hmcts.net/jira/browse/RDM-4345
Add retries to ES index verification in case ES has been setup in asynchronous mode
```
[ ] Yes
[x] No
```
> RDM-4345 - add retry for ES index verification

- src/main/resources/db/changelog/db.changelog-RDM-5190.xml
- src/main/resources/db/changelog/db.changelog-master.xml
…eCaseReference index.
https://tools.hmcts.net/jira/browse/RDM-5190
Add CMC jsonb indexes
Add index on `previousServiceCaseReference` field in all environments (DEMO, AAT, PRODUCTION)
No old index on the the old field called `referenceNumber` existed before so no need to drop.
```
[ ] Yes
[x] No
```
> RDM-5190 Add new previousServiceCaseReference index.

- src/main/resources/db/changelog/db.changelog-RDM-5110.xml
- src/main/resources/db/changelog/db.changelog-master.xml
https://tools.hmcts.net/jira/browse/RDM-5110
Create a UNIQUE constraint on case external id for CMC.
```
[ ] Yes
[ x] No
```
>  RDM-5110 UNIQUE index on case external id

- src/main/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/callbacks/RestTemplateProvider.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/DefaultCreateCaseOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/SubmitCaseTransaction.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/MidEventCallback.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpoint.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackServiceWireMockTest.java
https://tools.hmcts.net/jira/browse/RDM-4452
Use HttpClient instead of building RestTemplate on each callback request.
```
[ ] Yes
[x] No
```
> Rdm 4522 http client

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-3551
```
[ ] Yes
[ x] No
```
> RDM-3551- upgraded owasp dependencycheck to 5.1.0

- lib/AI-Agent.xml
RDM-4864
Add instrumentation support for CCD-AM integration Phase 1 - CaseTypeACL data integration b/w CCD & AM.
No
> RDM-4864 - Add instrumentation support for CCD-AM integration Phase 1

- charts/ccd-data-store-api/values.yaml
- infrastructure/variables.tf
N/A
Register employment_tribunals and ethos_repl_service as an authorised consumer service for data store 
```
[ ] Yes
[x] No
```
> Add employment_tribunals and ethos_repl_service to authorised services

- src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpoint.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/std/DraftsEndpoint.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/DraftsEndpointTest.java
https://tools.hmcts.net/jira/browse/RDM-5094
Add missing API path variables to the method signature to fix swagger API docs validation errors
```
[ ] Yes
[x] No
```
> RDM-5094 - add missing path variable

- infrastructure/variables.tf
> Update variables.tf with ctsc_work_allocation

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-5664
Fix CVE-2019-7614 
```
[ ] Yes
[X] No
```
> RDM-5664 Temporary suppression.

- charts/ccd-data-store-api/Chart.yaml
> RDM-5638- bumped chart version

- charts/ccd-data-store-api/values.yaml
- infrastructure/main.tf
- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepository.java
- src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/RDM-5650
removed duplicate search criteria (JPA) in DefaultCaseDetaRespository.
```
[ ] Yes
[ x] No
```
> RDM-5650 - remove duplicate search criteria (JPA) 

- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.yaml
> RDM-5913: fix outdated docker image url

- Jenkinsfile_CNP
- build.gradle
- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/requirements.yaml
- charts/ccd-data-store-api/values.aat.template.yaml
- charts/ccd-data-store-api/values.yaml
- dependency-check-suppressions.xml
> enabling aks

- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.preview.template.yaml
- charts/ccd-data-store-api/values.yaml
> Disable db migration

- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.yaml
> aligning authorised services on AKS with the one on ASE

- build.gradle
Updated cucumber config after breaking change
```
[ ] Yes
[ X ] No
```
> RDM-6329 update cucumber config

- build.gradle
- dependency-check-suppressions.xml
> RDM4313-specific changes applied

- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperation.java
- src/main/java/uk/gov/hmcts/ccd/v2/internal/resource/UIStartTriggerResource.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/CaseRolesIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/CaseRolesTestData.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/StartTriggerControllerCaseRolesIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UIStartTriggerControllerCaseRolesIT.java
- src/test/resources/mappings/case-roles-definition.json
https://tools.hmcts.net/jira/browse/RDM-6521
It is the https://github.com/hmcts/ccd-data-store-api/pull/604 based on the respondent-journey branch.
```
[ ] Yes
[ X] No
```
> RDM-6521 include CREATOR case role in the event trigger endpoints

- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/AuthorisedCreateCaseOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperation.java
- src/main/java/uk/gov/hmcts/ccd/v2/internal/resource/UIStartTriggerResource.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/createcase/AuthorisedCreateCaseOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/createcase/DefaultCreateCaseOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointUserRolesIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/CaseRolesIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/CaseRolesTestData.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerTestIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/StartTriggerControllerCaseRolesIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UIStartTriggerControllerCaseRolesIT.java
- src/test/resources/mappings/bookcase-create-on-creatorrole-definition.json
- src/test/resources/mappings/bookcase-no-create-on-creatorrole-definition.json
- src/test/resources/mappings/case-roles-definition.json
> Respondent journey rdm 6520

- build.gradle
n/a
Add temporary Sonar coverage exclusions for quality gate
```
[ ] Yes
[x] No
```
> Add temporary ITHC coverage exclusions

- build.gradle
n/a
Disable failing smoke tests in ITHC
```
[ ] Yes
[x] No
```
> Disable failing smoke tests in ITHC

- web.config
https://tools.hmcts.net/jira/browse/RDM-5533
Disable `X-Powered-By` header
```
[ ] Yes
[x] No
```
> RDM-5533 Disable X-Powered-By header

- src/aat/resources/features/F-050/F-050.feature
- src/aat/resources/features/F-050/F-050_Common_Data_In_Body.td.json
- src/aat/resources/features/F-050/F-050_Test_Data_Base.td.json
- src/aat/resources/features/F-050/S-297.td.json
- src/aat/resources/features/F-050/S-298.td.json
- src/aat/resources/features/F-050/S-299.td.json
- src/aat/resources/features/F-050/S-300.td.json
- src/aat/resources/features/F-050/S-301.td.json
https://tools.hmcts.net/jira/browse/RDM-6323
Implement Functional Tests for 'Validate a set of fields as Case worker' operation
[ ] Yes
[x] No
> RDM-6323: Functional Tests for 'Validate a set of fields as Case worker' operation

- src/aat/resources/features/F-049/F-049.feature
- src/aat/resources/features/F-049/F-049_Test_Data_Base.td.json
- src/aat/resources/features/F-049/S-231.td.json
- src/aat/resources/features/F-049/S-232.td.json
- src/aat/resources/features/F-049/S-233.td.json
- src/aat/resources/features/F-049/S-234.td.json
- src/aat/resources/features/F-049/S-235.td.json
- src/aat/resources/features/F-049/S-511.td.json
- src/aat/resources/features/F-049/S-512.td.json
- src/aat/resources/features/F-049/S-513.td.json
https://tools.hmcts.net/jira/browse/RDM-6320
Implement Functional Tests for 'CCD Data Store API:: Start case creation as Caseworker' operation
```
[ ] Yes
[x ] No
```
> RDM-6320 start case creation as case worker-BE-FAT

- src/aat/java/uk/gov/hmcts/ccd/fta/steps/BackEndFunctionalTestScenarioPlayer.java
https://tools.hmcts.net/jira/browse/RDM-6557
```
[ ] Yes
[ ] No
```
> RDM-6557: Added the file upload functionality.

- src/aat/resources/features/F-049/S-512.td.json
- src/aat/resources/features/F-058/S-518.td.json
https://tools.hmcts.net/jira/browse/RDM-6320
Jenkins fail due to Not Found missing form expected Result for S-512 and S-518 
```
[ ] Yes
[x ] No
```
> Rdm 6320 jenkins fails

- src/aat/java/uk/gov/hmcts/ccd/fta/data/HttpTestData.java
- src/aat/java/uk/gov/hmcts/ccd/fta/exception/FunctionalTestException.java
- src/aat/java/uk/gov/hmcts/ccd/fta/steps/BackEndFunctionalTestAutomationDSL.java
- src/aat/java/uk/gov/hmcts/ccd/fta/steps/BackEndFunctionalTestScenarioContext.java
- src/aat/java/uk/gov/hmcts/ccd/fta/steps/BackEndFunctionalTestScenarioPlayer.java
- src/aat/java/uk/gov/hmcts/ccd/fta/steps/DynamicValueInjector.java
- src/aat/java/uk/gov/hmcts/ccd/fta/steps/DynamicValueInjectorTest.java
- src/aat/resources/features/F-037/S-024.td.json
- src/aat/resources/features/common/case/Standard_Full_Case_Creation_Data.td.json
- src/aat/resources/features/common/case/Standard_Token_Creation_Data_For_Case_Creation.td.json
- src/aat/resources/framework-test-data/field-injector-test-data/Simple-Test-Data-With-All-Possible-Dynamic-Values.td.json
- src/aat/resources/framework-test-data/field-injector-test-data/Token_Creation_Call.td.json
> Rdm 6874 test

- src/aat/resources/features/F-026/F-026.feature
- src/aat/resources/features/F-026/F-026_Test_Data_Base.td.json
- src/aat/resources/features/F-026/S-074.td.json
- src/aat/resources/features/F-026/S-075.td.json
- src/aat/resources/features/F-026/S-076.td.json
- src/aat/resources/features/F-026/S-077.td.json
- src/aat/resources/features/F-026/S-078.td.json
https://tools.hmcts.net/jira/browse/RDM-6385
Creating functional test cases for "Get case data with UI layout" endpoint
[ ] Yes
[x] No
> RDM-6385: functional test cases for "Get case data with UI layout"

- src/aat/resources/features/F-063/F-063.feature
- src/aat/resources/features/F-063/F-063_Base_Test_Data.td.json
- src/aat/resources/features/F-063/S-213.td.json
- src/aat/resources/features/F-063/S-214.td.json
- src/aat/resources/features/F-063/S-215.td.json
- src/aat/resources/features/F-063/S-561.td.json
- src/aat/resources/features/F-063/S-XXX.td.json
https://tools.hmcts.net/jira/browse/RDM-6427
Added functional tests for the Retrieve search input details endpoint
```
[ ] Yes
[x] No
```
> RDM-6427 Functional tests for Retrieve search input details for dynamic display

- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/WizardPageField.java
https://tools.hmcts.net/jira/browse/RDM-6887
Removed displayContext from WizardPageField
```
[ ] Yes
[X ] No
```
> RDM-6887 Remove duplicate display context from data store endpoint

- src/aat/resources/features/F-052/F-052.feature
- src/aat/resources/features/F-052/F-052_Case_Creation_Citizen_Role.td.json
- src/aat/resources/features/F-052/F-052_Test_Data_Base.td.json
- src/aat/resources/features/F-052/S-069.td.json
- src/aat/resources/features/F-052/S-070.td.json
- src/aat/resources/features/F-052/S-071.td.json
- src/aat/resources/features/F-052/S-072.td.json
https://tools.hmcts.net/jira/browse/RDM-6384
Implement functional test cases for "Get case data for a given case type for Citizen" operation until it has at least a 'good' level of functional test coverage.
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> RDM-6384 : Implement functional test cases for "Get case data for a given case type for Citizen" endpoint

- build.gradle
- src/aat/resources/features/F-054/F-054.feature
- src/aat/resources/features/F-054/F-054_Test_Data_Base.td.json
- src/aat/resources/features/F-054/S-093.td.json
https://tools.hmcts.net/jira/browse/RDM-6421
Implement Functional Tests for 'CCD Data Store Api :: Get case for Citizen' operation
```
[ ] Yes
[ x ] No
```
> Rdm 6421 get case for citizen

- src/aat/java/uk/gov/hmcts/ccd/datastore/befta/DataStoreTestAutomationAdapter.java
https://tools.hmcts.net/jira/browse/RDM-7086
add preconfiguration of ccd roles needed for fta
```
[ ] Yes
[X] No
```
> added preconfiguration of ccd roles needed for fta

- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/JurisdictionMapper.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/CachedUIDefinitionGateway.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/HttpUIDefinitionGateway.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/UIDefinitionGateway.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/UIDefinitionRepository.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/JurisdictionDisplayProperties.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/Banner.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/BannersResult.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/Jurisdiction.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetBannerOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/GetBannerOperation.java
- src/main/java/uk/gov/hmcts/ccd/v2/V2.java
- src/main/java/uk/gov/hmcts/ccd/v2/internal/controller/UIDefinitionController.java
- src/main/java/uk/gov/hmcts/ccd/v2/internal/resource/UIBannerResource.java
- src/test/java/uk/gov/hmcts/ccd/data/casedetails/JurisdictionMapperTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetUserProfileOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetBannerOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UIDefinitionControllerTest.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/resource/UIBannerResourceTest.java
https://tools.hmcts.net/jira/browse/RDM-6719
Display Banner on CCD UI for each Jurisdiction configured.
```
[ ] Yes
[ X] No
> RDM-6719: Add Banner Feature to CCD UI

- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-7116
```
[ ] Yes
[x] No
```
> RDM-7116-rm-ase-envir

- src/aat/resources/features/F-037/F-037.feature
- src/aat/resources/features/F-037/S-577-Prerequisite_Solicitor_1_Token_For_Update_Case.td.json
- src/aat/resources/features/F-037/S-577-Prerequisite_Solicitor_2_Token_For_Update_Case.td.json
- src/aat/resources/features/F-037/S-577-Prerequisite_Solicitor_3_Token_For_Update_Case.td.json
- src/aat/resources/features/F-037/S-577.td.json
- src/aat/resources/features/F-037/S-577_Get_Case_For_Case_Worker_Data_Base.td.json
- src/aat/resources/features/F-037/S-577_Later_Case_Read_By_Solicitor_1.td.json
- src/aat/resources/features/F-037/S-577_Later_Case_Read_By_Solicitor_3.td.json
- src/aat/resources/features/F-037/S-577_Later_Case_Update_By_Solicitor_1.td.json
- src/aat/resources/features/F-037/S-577_Later_Case_Update_By_Solicitor_3.td.json
- src/aat/resources/features/F-037/S-577_Response_Data_Base.td.json
- src/aat/resources/features/F-037/S-577_Response_Data_Classification.td.json
- src/aat/resources/features/F-037/S-577_Response_Data_Common.td.json
- src/aat/resources/features/F-037/S-577_Update_Case_For_Case_Worker_Data_Base.td.json
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDM-7068
Implement functional test cases for "Automate AM Scenarios for F037 Create_EventV2" operation until it has at least a 'good' level of functional test coverage.
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> RDM-7068 : Automate AM Scenarios for F037 Create_EventV2

- src/aat/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Token_For_Update_Case.td.json
RDM-7222
```
[ ] Yes
[ ] No
```
> RDM-7222: Addeed common update file.

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-7289
Update jackson-databind
```
[ ] Yes
[x] No
```
> RDM-7289 - Update jackson-databind

- infrastructure/aat.tfvars
- infrastructure/ithc.tfvars
- infrastructure/perftest.tfvars
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/sprod.tfvars
Reverts hmcts/ccd-data-store-api#746
> Revert "Remove unwanted env (ASE) files"

- build.gradle
- src/main/java/uk/gov/hmcts/ccd/AppInsights.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/DefaultCaseDefinitionRepository.java
https://tools.hmcts.net/jira/browse/RDM-7313
Sonar build xml reporting
```
[ ] Yes
[ X] No
```
> RDM-7313: Use Jacoco XML report for SonarCloud

- build.gradle
temp exclusion of classes from sonar so build passes which unblocks other builds 
```
[ ] Yes
[x] No
```
> Temp sonar exclusions

- src/test/java/uk/gov/hmcts/ccd/data/definition/DefaultCaseDefinitionRepositoryTest.java
- src/test/java/uk/gov/hmcts/ccd/data/definition/HttpUIDefinitionGatewayServiceExceptionTest.java
- src/test/java/uk/gov/hmcts/ccd/data/definition/HttpUIDefinitionGatewayTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetUserProfileOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/integrations/DefinitionsCachingIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UIDefinitionControllerTest.java
- src/test/resources/mappings/banner-definitions.json
https://tools.hmcts.net/jira/browse/RDM-7380
https://tools.hmcts.net/jira/browse/RDM-7312
Introduce code coverage reports for the banner changes
```
[ ] Yes
[X ] No
```
> Rdm 7380: Fix cod coverage issue on Banner Changes

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
https://tools.hmcts.net/jira/browse/RDM-6943
```
[ ] Yes
[X] No
```
> RDM-6943 Replace Open Passwords with Environment Vars in all Test Data

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-7466
The "specs" field in a test data inheritance case is not properly inherited.
The inheritance mechanism should append the elements of an array in a json object to the list of inherited elements from the extended object.
```
[ ] Yes
[X] No
```
> bump up fw version to new release

- charts/ccd-data-store-api/values.preview.template.yaml
- src/aat/resources/features/F-051/S-110.td.json
> Add definition store host for preview backend

- src/test/java/uk/gov/hmcts/ccd/data/definition/HttpUIDefinitionGatewayTest.java
- src/test/resources/mappings/jurisdiction-ui-configs-definitions.json
> HttpUIDefinitionGateway coverage

- build.gradle
- src/aat/resources/features/F-000/S-000-Prerequisite.td.json
- src/aat/resources/features/F-000/S-000.td.json
- src/aat/resources/features/F-026/S-078.td.json
- src/aat/resources/features/F-028/S-044.td.json
- src/aat/resources/features/F-029/S-049.td.json
- src/aat/resources/features/F-042/S-246.td.json
- src/aat/resources/features/F-046/S-222.td.json
- src/aat/resources/features/F-047/F-047_Test_Data_Base.td.json
- src/aat/resources/features/F-051/S-110.td.json
- src/aat/resources/features/F-065/F-065_Test_Data_Base.td.json
- src/aat/resources/features/F-065/S-162.td.json
- src/aat/resources/features/F-065/S-580.td.json
- src/aat/resources/features/F-065/S-581.td.json
- src/aat/resources/features/F-102/F-102_Test_Data_Base.td.json
- src/aat/resources/features/F-102/S-559.td.json
https://tools.hmcts.net/jira/browse/RDM-7583
correct check for unexpectedly unavailable values
```
[ ] Yes
[X] No
```
> version bumb-up for fixed fw version

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepository.java
> Hotfix add UUID to log messages

- build.gradle
> Upgrade to befta 1.1.1

- src/main/java/uk/gov/hmcts/ccd/domain/model/callbacks/CallbackResponse.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/stdapi/CallbackInvokerTest.java
https://tools.hmcts.net/jira/browse/RDM-7669
Always remove data state override
Supersedes #814  
```
[ ] Yes
[x] No
```
> RDM-7669 - Always remove data state override - MASTER

- src/aat/resources/features/F-026/F-026.feature
- src/aat/resources/features/F-027/F-027.feature
- src/aat/resources/features/F-028/F-028.feature
- src/aat/resources/features/F-029/F-029.feature
- src/aat/resources/features/F-034/F-034.feature
- src/aat/resources/features/F-036/F-036.feature
- src/aat/resources/features/F-037/F-037.feature
- src/aat/resources/features/F-042/F-042.feature
- src/aat/resources/features/F-044/F-044.feature
- src/aat/resources/features/F-045/F-045.feature
- src/aat/resources/features/F-046/F-046.feature
- src/aat/resources/features/F-047/F-047.feature
- src/aat/resources/features/F-048/F-048.feature
- src/aat/resources/features/F-050/F-050.feature
- src/aat/resources/features/F-051/F-051.feature
- src/aat/resources/features/F-052/F-052.feature
- src/aat/resources/features/F-053/F-053.feature
- src/aat/resources/features/F-055/F-055.feature
- src/aat/resources/features/F-056/F-056.feature
- src/aat/resources/features/F-057/F-057.feature
- src/aat/resources/features/F-059/F-059.feature
- src/aat/resources/features/F-064/F-064.feature
- src/aat/resources/features/F-065/F-065.feature
- src/aat/resources/features/F-066/F-066.feature
- src/aat/resources/features/F-067/F-067.feature
- src/aat/resources/features/F-101/F-101.feature
- src/aat/resources/features/F-102/F-102.feature
https://tools.hmcts.net/jira/browse/RDM-6847
Ignoring 403 test cases where token validation fails. Will be rewritten as part of RDM-6847
```
[ ] Yes
[ ] No
```
> Ignoring 403 test cases where token validation fails. Will be rewritten as part of RDM-6847

- src/test/java/uk/gov/hmcts/ccd/data/definition/CaseDefinitionRepositoryWireMockNotRunningTest.java
https://tools.hmcts.net/jira/browse/RDM-7986
Reenable smoke and functional tests
```
[ ] Yes
[X] No
```
> re-enable flaky tests for diagnostic

- Jenkinsfile_CNP
- charts/ccd-data-store-api/values.preview.template.yaml
- src/test/java/uk/gov/hmcts/ccd/data/definition/CaseDefinitionRepositoryWireMockNotRunningTest.java
https://tools.hmcts.net/jira/browse/RDM-7986
Reenable smoke and functional tests
```
[ ] Yes
[X] No
```
> re-enable tests for diagnostic

- build.gradle
- src/aat/java/uk/gov/hmcts/ccd/datastore/tests/fixture/CCDEventBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseAuditEventMapper.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseDetailsMapper.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseDataService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/DefaultObjectMapperService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityValidationService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/AuthorisedCreateCaseOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/AuthorisedCreateEventOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/getcase/AuthorisedGetCaseOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/AuthorisedSearchOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperation.java
- src/main/java/uk/gov/hmcts/ccd/v2/external/controller/CaseDataValidatorController.java
- src/test/java/uk/gov/hmcts/ccd/BaseTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseDataServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/createevent/AuthorisedCreateEventOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/createevent/MidEventCallbackTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/AuthorisedSearchOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/CaseDataValidatorTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/PostCodeValidatorTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/YesNoValidatorTest.java
https://tools.hmcts.net/jira/browse/RDM-8013
CVE issues fixed on jackson-databind
```
[ ] Yes
[ X] No
```
> Rdm 8013: CVE failures on data-store-api deployment to Demo

- .github/workflows/swagger.yml
- src/test/java/uk/gov/hmcts/ccd/swagger/SwaggerPublisher.java
https://tools.hmcts.net/jira/browse/RDM-7740
Establish automated publishing of swagger spec with a github workflow (fix applied)
```
[ ] Yes
[X] No
```
> introduce test class and github action to publish swagger specs

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/ithc.tfvars
- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
> add missing vars

- .github/workflows/swagger.yml
> update to swagger.yml

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-8156
Upgrade to fixed fw version
```
[ ] Yes
[X] No
```
> regression test am-649 fix on data store

- .github/workflows/swagger.yml
> RDM-7740 : added jenkins-reform-cdm instead nobody as the username.

- build.gradle
bump up fw version
```
[ ] Yes
[X] No
```
> Bump up fw version

- src/aat/resources/features/F-063/S-215.td.json
- src/aat/resources/features/F-063/S-595.td.json
- src/aat/resources/features/F-064/S-558.td.json
- src/aat/resources/features/F-064/S-596.td.json
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CriteriaField.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/search/Field.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetCriteriaOperation.java
- src/main/java/uk/gov/hmcts/ccd/v2/internal/resource/UISearchInputsResource.java
- src/main/java/uk/gov/hmcts/ccd/v2/internal/resource/UIWorkbasketInputsResource.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetCriteriaOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UIDefinitionControllerIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UIDefinitionControllerTest.java
- src/test/resources/mappings/SearchInputDefinition.json
- src/test/resources/mappings/workbasket-input-definitions.json
https://tools.hmcts.net/jira/browse/RDM-7801
```
[ ] Yes
[ x] No
```
> RDM-7801 - showCondition in input filters apis

- src/main/java/uk/gov/hmcts/ccd/domain/types/DateTimeValidator.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/DateValidator.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/DateTimeValidatorTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/DateValidatorTest.java
https://tools.hmcts.net/jira/browse/RDM-8249
Update Date/DateTime validation error messages
```
[ ] Yes
[x] No
```
> RDM-8249 - Update Date/DateTime validation error messages

- .github/workflows/swagger.yml
- build.gradle
- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/config/SwaggerConfiguration.java
- src/test/java/uk/gov/hmcts/ccd/swagger/SwaggerGeneratorTest.java
https://tools.hmcts.net/jira/browse/RDM-7740
Establish automated publishing of swagger spec with a github workflow (fix applied)
```
[ ] Yes
[X] No
```
> Rdm 7740 final

- README.md
https://tools.hmcts.net/jira/browse/RDM-8222
readme update for remediation of integration test failures due to pg failure
```
[ ] Yes
[X] No
```
> Rdm 8222 readme update

- charts/ccd-data-store-api/values.preview.template.yaml
- src/main/java/uk/gov/hmcts/ccd/domain/service/processor/DateTimeEntryProcessor.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/processor/DateTimeValueFormatter.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/processor/FieldProcessor.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/processor/SearchResultProcessor.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/processor/DateTimeEntryProcessorTest.java
https://tools.hmcts.net/jira/browse/RDM-8333
Update FieldProcessor for Complex types to iterate through JsonNode data rather than Complex case fields
```
[ ] Yes
[x] No
```
> RDM-8333 - Demo issue - Unable to create a case

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/CriterionFactory.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/MetaData.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/SearchQueryOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/processor/SearchInputProcessor.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpoint.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpoint.java
- src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/MetaDataTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/SearchQueryOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/processor/SearchInputProcessorTest.java
https://tools.hmcts.net/jira/browse/RDM-8269
Add handling for metadata criteria inputs
```
[ ] Yes
[x] No
```
> RDM-8269 - Add datetime formatting handling for metadata criteria inputs

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/ccd/domain/service/processor/SearchResultProcessor.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/processor/SearchResultProcessorTest.java
https://tools.hmcts.net/jira/browse/RDM-8402
Handle MultiSelectList types in search/workbasket results
```
[ ] Yes
[x] No
```
> RDM-8402 - Handle MultiSelectList types in search/workbasket results

- src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/SubmitCaseTransaction.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/CreateCaseEventService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentAttacher.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentAttacherTest.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerEventsIT.java
- src/test/resources/tests/case-update-payload-it.json
> Am 588 create case upload document development

- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.yaml
- dependency-check-suppressions.xml
> RDM-8445-PCQ

- Jenkinsfile_nightly
- build.gradle
> Add Mutation tests - by Pettedson

- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.yaml
Added ecm_consumer to authorised services
```
[ ] Yes
[X] No
```
> Added ecm_consumer to authorised services

- build.gradle
- src/aat/java/uk/gov/hmcts/ccd/datastore/befta/DataStoreBeftaMain.java
- src/aat/java/uk/gov/hmcts/ccd/datastore/befta/EmptySmokeTest.java
> remove all except for befta smoke tests from smoke

- Jenkinsfile_CNP
- dependency-check-suppressions.xml
> rm-installCharts

- src/main/resources/db/changelog/db.changelog-RDM-8485.xml
- src/main/resources/db/changelog/db.changelog-master.xml
https://tools.hmcts.net/jira/browse/RDM-8485
Added new indexes that are already added in Prod as part of P1.
```
[ ] Yes
[X] No
```
> Added db ChnageLog for new indexes created as part of RDM-8485

- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/dto/ElasticSearchCaseDetailsDTO.java
https://tools.hmcts.net/jira/browse/RDM-8552
Add last_state_modified_date for ES query responses
```
[ ] Yes
[x] No
```
> RDM-8552 - Add last_state_modified_date to ES CaseDetails DTO

- build.gradle
- src/aat/resources/features/F-103/S-597.td.json
- src/aat/resources/features/F-103/S-598.td.json
- src/aat/resources/features/F-103/S-599.td.json
- src/aat/resources/features/F-103/S-600.td.json
https://tools.hmcts.net/jira/browse/RDM-8759
introduce use of comma-separated list to describe a composite id
```
[ ] Yes
[X] No
```
> introduce use of composite keys for unordered equivalence checks

- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseAssignedUserRolesControllerIT.java
https://tools.hmcts.net/jira/browse/RDM-8764
Fixing failed integration tests
```
[ ] Yes
[X ] No
```
> RDM-8764: Integration tests failing after OIDC changes on CaseAssignedUserRolesController

- src/main/java/uk/gov/hmcts/ccd/domain/model/search/CommonViewHeader.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/search/CommonViewItem.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/search/SearchResultViewColumn.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/search/SearchResultViewItem.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/search/elasticsearch/SearchResultViewHeader.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/search/elasticsearch/SearchResultViewItem.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/MergeDataToSearchResultOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/processor/SearchResultProcessor.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/CaseSearchResultGenerator.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/ElasticsearchSortService.java
- src/main/java/uk/gov/hmcts/ccd/v2/internal/controller/UICaseSearchController.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/CaseSearchResultGeneratorTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/MergeDataToSearchResultOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/processor/SearchResultProcessorTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/ElasticsearchSortServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/SearchWithSortIT.java
https://tools.hmcts.net/jira/browse/RDM-8460
Implement date formatting for the internal ES API response
```
[ ] Yes
[x] No
```
> RDM-8460 - Implement date formatting for the internal ES API response

- src/main/java/uk/gov/hmcts/ccd/data/SecurityUtils.java
- src/test/java/uk/gov/hmcts/ccd/MockUtils.java
- src/test/java/uk/gov/hmcts/ccd/data/SecurityUtilsTest.java
> Correcting idam claim type 

- build.gradle
> upgrade fw version

- build.gradle
> CVE 11996 Fix

- build.gradle
[RDM-8895](https://tools.hmcts.net/jira/browse/RDM-8895) _"BEFTA FW extension: add prerequisites references to test data definition"_
BEFTA FW extension: add prerequisites references to test data definition.
```
[ ] Yes
[x] No
```
> RDM-8895 BEFTA FW extension: add prerequisites references to test data definition

- build.gradle
- src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/CreateCaseEventService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/validate/DefaultValidateCaseFieldsOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/validate/ValidateCaseFieldsOperation.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/validate/DefaultValidateCaseFieldsOperationTest.java
https://tools.hmcts.net/jira/browse/RDM-8993
Validate OrgPolicyCaseAssignedRole on event update
```
[ ] Yes
[X ] No
```
> RDM-8993: Update event API: There's no validation on default value of organisation policy case assigned role

- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.yaml
N/A
added civil unspec service to whitelisted services
```
[ ] Yes
[x] No
```
> dev: added civil unspec service to whitelisted services (CMC-NA)

- build.gradle
- src/aat/resources/features/F-035/F-035.feature
- src/aat/resources/features/F-035/F-035_Base_Test_Data.td.json
- src/aat/resources/features/F-035/S-035.01_Case.td.json
- src/aat/resources/features/F-035/S-035.01_Case_Token_Creation.td.json
- src/aat/resources/features/F-035/S-035.01_GetToken.td.json
- src/aat/resources/features/F-035/S-591.td.json
- src/aat/resources/features/F-063/F-063_Base_Test_Data.td.json
- src/aat/resources/features/F-063/S-595.td.json
https://tools.hmcts.net/jira/browse/ACA-11
Upgrade to framework 5.0 after aca-11 changes in it.
```
[] Yes
[X] No
```
> use latest prerelease

- src/main/resources/db/changelog/db.changelog-RDM-8463.xml
- src/main/resources/db/changelog/db.changelog-master.xml
https://tools.hmcts.net/jira/browse/RDM-8463
Adding db ChangeLog for new indexes created as part of RDM-8463
```
[ ] Yes
[X] No
```
> Adding db ChangeLog for new indexes created as part of RDM-8463

- Jenkinsfile_CNP
- build.gradle
- src/main/resources/db/changelog/db.changelog-RDM-8463.xml
- src/main/resources/db/changelog/db.changelog-master.xml
* Adding db ChangeLog for new indexes created as part of RDM-8463
* Adding db ChangeLog for new indexes created as part of RDM-8463
* Removed duplicate entry
Co-authored-by: sumansreenivasan <anuManu10>
Co-authored-by: Olawale Olanrewaju <olanrewajume@yahoo.com>
```
[ ] Yes
[ ] No
```
> Adding db ChangeLog for new indexes created as part of RDM-8463 (#959)

- .github/workflows/swagger.yml
- .travis.yml
- Jenkinsfile_CNP
- README.md
- charts/ccd-data-store-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-9231
Changed
v1 -> v1_internal v1_external
v2 -> v2_internal v2_external
```
[ ] Yes
[ X] No
```
> RDM-9231 Fix Swagger groups

- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/requirements.yaml
- charts/ccd-data-store-api/values.yaml
> Revert "removed es and ls dependencies"

- Jenkinsfile_CNP
- build.gradle
enhance pipeline logic per build type
```
[ ] Yes
[X] No
```
> enhance pipeline logic per build type

- charts/ccd-data-store-api/Chart.yaml
> Update Chart.yaml fix depend

- dependency-check-suppressions.xml
> RDM 9008 add dependency suppression

- dependency-check-suppressions.xml
> add temporary suppressions

- src/main/java/uk/gov/hmcts/ccd/data/definition/DefaultCaseDefinitionRepository.java
- src/main/java/uk/gov/hmcts/ccd/v2/internal/controller/UICaseSearchController.java
> removing sonar bugs

- src/main/java/uk/gov/hmcts/ccd/domain/model/search/CaseSearchResult.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/ElasticsearchCaseSearchOperationTest.java
https://tools.hmcts.net/jira/browse/RDM-9448
undo temporary removal of case_types_results
```
[ ] Yes
[X] No
```
> undo temporary removal of case_types_results

- src/main/java/uk/gov/hmcts/ccd/domain/model/search/CaseSearchResult.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/ElasticsearchCaseSearchOperationTest.java
> Release cut 19.2

- src/main/java/uk/gov/hmcts/ccd/domain/model/search/CaseSearchResult.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/ElasticsearchCaseSearchOperationTest.java
https://tools.hmcts.net/jira/browse/RDM-9448
undo temporary removal of case_types_results
```
[ ] Yes
[X] No
```
> revert temporary removal of case types results

- src/aat/resources/features/F-053/S-269.td.json
- src/aat/resources/features/F-105 - Add Case-Assigned Users and Roles/Without Organisation Context/S-105.1.verify.td.json
> Fix broken build

- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/domain/types/ApprovalStatusValidator.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/ApprovalStatusValidatorTest.java
https://tools.hmcts.net/jira/browse/RDM-9266
Introduce ChangeOrganisationRequest base type validation for ApprovalStatus field
```
[ ] Yes
[ X] No
```
> RDM-9266: Introduce ChangeOrganisationRequest Complex Field Standard Base Type

- build.gradle
> upgrade to fw 5.7.1

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-9522
Use latest version of `befta-fw`
```
[ ] Yes
[X] No
```
> RDM-9522 - Update with befta-fw pre-release tag

- build.gradle
- src/aat/java/uk/gov/hmcts/ccd/datastore/befta/DataStoreTestAutomationAdapter.java
https://tools.hmcts.net/jira/browse/RDM-9238
treat skipped scenarios as passed
```
[ ] Yes
[X] No
```
> treat skipped scenarios as passed

- charts/ccd-data-store-api/values.preview.template.yaml
> Fix develop

- src/aat/resources/features/F-115/F-115.feature
> Reserve ID for functional tests

- src/main/java/uk/gov/hmcts/ccd/data/definition/HttpUIDefinitionGateway.java
- src/main/java/uk/gov/hmcts/ccd/data/draft/DefaultDraftGateway.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetails.java
> Sonar suppressions for old code

- Jenkinsfile_CNP
- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-9424
Fix CVE-2020-7019
```
[ ] Yes
[X] No
```
> RDM-9424 : CVE fixes

- Jenkinsfile_CNP
- build.gradle
> temporarily exclude sonar on newly failing classes.

- charts/ccd-data-store-api/values.preview.template.yaml
> Use hmctspublic for logstash

- src/main/java/uk/gov/hmcts/ccd/auditlog/AuditService.java
- src/main/java/uk/gov/hmcts/ccd/data/user/DefaultUserRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/user/UserService.java
- src/test/java/uk/gov/hmcts/ccd/auditlog/AuditServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseAccessEndpointIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseSearchEndpointIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerTestIT.java
https://tools.hmcts.net/jira/browse/RDM-9250
Removed PII from application logs
```
[ ] Yes
[X ] No
```
> RDM-9250: Identify and remove PII (Personally Identifiable Information) from CCD logs

- src/aat/resources/features/F-109/S-947.td.json
> Fix test data

- dependency-check-suppressions.xml
CVE Temporary Suppression for <cve>CVE-2020-5421</cve>
```
[ ] Yes
[X] No
```
> CVE Temporary Suppression

- build.gradle
- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
https://tools.hmcts.net/jira/browse/RDM-9480
Fix All Temporarily Suppressed CVEs - Data Store Api
```
[ ] Yes
[X] No
```
> Rdm 9480 hazel cast liquibase

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-9113
Migrate DataStore to use HMCTS Gradle Java Plugin
```
[ ] Yes
[x] No
```
> bump up hmcts plugin version

- src/main/resources/db/changelog/db.changelog-RDM-9696.xml
- src/main/resources/db/changelog/db.changelog-master.xml
https://tools.hmcts.net/jira/browse/RDM-9696
```
[ ] Yes
[X] No
```
> Added db changelog for RDM-9696

- src/main/java/uk/gov/hmcts/ccd/domain/service/search/CaseSearchResultViewGenerator.java
> RDM-9333: Remove labels from the response to internal search API

- src/main/java/uk/gov/hmcts/ccd/domain/service/search/CaseSearchResultViewGenerator.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/CaseSearchesViewAccessControl.java
> Checkstyle for RDM-9868+Release-20.1

- build.gradle
> RDM-9925 bump up befta version

- build.gradle
- dependency-check-suppressions.xml
> Frmework bump up

- src/aat/java/uk/gov/hmcts/ccd/datastore/befta/DataStoreTestAutomationAdapter.java
- src/aat/resources/features/F-125 - Swagger Pages and API Specs/F-125.feature
- src/aat/resources/features/F-125 - Swagger Pages and API Specs/F-125_Swagger_JSON.td.json
- src/aat/resources/features/F-125 - Swagger Pages and API Specs/F-125_Swagger_UI.td.json
- src/aat/resources/features/F-125 - Swagger Pages and API Specs/S-125.1.td.json
- src/aat/resources/features/F-125 - Swagger Pages and API Specs/S-125.2.td.json
- src/aat/resources/features/F-125 - Swagger Pages and API Specs/S-125.3.td.json
- src/aat/resources/features/F-125 - Swagger Pages and API Specs/S-125.4.td.json
- src/aat/resources/features/F-125 - Swagger Pages and API Specs/S-125_Swagger_JSON_V1_External.td.json
- src/aat/resources/features/F-125 - Swagger Pages and API Specs/S-125_Swagger_JSON_V1_Internal.td.json
- src/aat/resources/features/F-125 - Swagger Pages and API Specs/S-125_Swagger_JSON_V2_External.td.json
- src/aat/resources/features/F-125 - Swagger Pages and API Specs/S-125_Swagger_JSON_V2_Internal.td.json
https://tools.hmcts.net/jira/browse/RDM-9200
Test to verify Swagger documentation is not broken
```
[ ] Yes
[X] No
```
> RDM-9200 Test to verify Swagger documentation is not broken

- build.gradle
- src/aat/resources/features/F-122 - Conditional Event Post States/F-122.feature
- src/aat/resources/features/F-122 - Conditional Event Post States/S-122.1.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/S-122.2.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/S-122.3.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/S-122.4.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/S-122.5.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/S-122.6.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/S-122.7.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/S-122.8.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/common/F-122-UpdateEventBase.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/common/FT_ConditionalPostState_Case_Data.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/common/FT_ConditionalPostState_Create_Case.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/common/S-122-GetToken_CaseCreate.td.json
- src/aat/resources/features/F-122 - Conditional Event Post States/common/S-122-GetToken_UpdateCase.td.json
https://tools.hmcts.net/jira/browse/RDM-9587
FTs for the Conditional Post States
```
[ ] Yes
[ X] No
```
> RDM-9587 FTs for the Conditional Post States

- src/aat/resources/features/F-027/S-590.td.json
- src/aat/resources/features/F-028/S-044.td.json
- src/aat/resources/features/F-029/S-049.td.json
- src/aat/resources/features/F-065/S-165.td.json
- src/aat/resources/features/F-104/S-628.td.json
- src/aat/resources/features/F-104/S-638.td.json
- src/aat/resources/features/F-109/S-946.td.json
- src/aat/resources/features/F-120 supplementary_data in ES Search API/S-120.2.td.json
- src/aat/resources/features/F-121/S-121.1.td.json
- src/aat/resources/features/F-121/S-121.2.td.json
- src/aat/resources/features/F-121/S-121.3.td.json
- src/aat/resources/features/F-121/S-121.4.td.json
- src/aat/resources/features/F-121/S-121.5.td.json
- src/aat/resources/features/F-121/S-121.6.td.json
- src/aat/resources/features/F-121/S-121.7.td.json
- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewField.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewFieldBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseEventFieldDefinition.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/WizardPageComplexFieldOverride.java
https://tools.hmcts.net/jira/browse/RDM-9954
Removed the defaultValue from the places where is not used and exposed through the API.
```
[ ] Yes
[X ] No
```
> RDM-9954 Remove defaultValue from the API

- src/aat/resources/features/F-109/F-109.feature
- src/aat/resources/features/F-120 supplementary_data in ES Search API/F-120.feature
- src/aat/resources/features/F-121/F-121.feature
> Temporarily disable FT relying on collection ordering

- src/main/java/uk/gov/hmcts/ccd/config/SwaggerConfiguration.java
> fix build after 20.1

- dependency-check-suppressions.xml
> fix suppression file

- src/aat/resources/features/F-114 - Notice Of Change/F-114.feature
> Temporarily disable FT

- src/test/java/uk/gov/hmcts/ccd/test/ElasticsearchTestHelper.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UICaseSearchControllerIT.java
- src/test/resources/elasticsearch/config/index-settings.json
- src/test/resources/elasticsearch/config/mappings-aat_cases.json
- src/test/resources/elasticsearch/config/mappings-mapper_cases.json
- src/test/resources/elasticsearch/config/mappings-restricted_security_cases.json
- src/test/resources/elasticsearch/config/mappings-security_cases.json
https://tools.hmcts.net/jira/browse/RDM-8698
```
[ ] Yes
[X] No
```
> RDM-8698 : Elasticsearch exact match queries on phone numbers with spaces never return results

- build.gradle
> Befta v21.1

- Jenkinsfile_CNP
> reenable es test on master by default

- charts/ccd-data-store-api/values.yaml
- liquibase.gradle
> Update gssEncMode 

- dependency-check-suppressions.xml
> Suppress CVE-2020-26168

- charts/ccd-data-store-api/Chart.yaml
> bump up chart version

- charts/ccd-data-store-api/values.yaml
- dependency-check-suppressions.xml
- liquibase.gradle
- src/main/java/uk/gov/hmcts/ccd/AliasWebConfig.java
- src/main/java/uk/gov/hmcts/ccd/SecurityConfiguration.java
https://tools.hmcts.net/jira/browse/RDM-10301
```
[ ] Yes
[ ] No
```
> Release cut demo deployment fix

- src/main/java/uk/gov/hmcts/ccd/data/SecurityUtils.java
- src/main/java/uk/gov/hmcts/ccd/data/user/DefaultUserRepository.java
- src/main/java/uk/gov/hmcts/ccd/security/JwtGrantedAuthoritiesConverter.java
- src/main/java/uk/gov/hmcts/ccd/security/idam/IdamRepository.java
https://tools.hmcts.net/jira/browse/RDM-10378
Improve Logging of User Info and User Roles
```
[ ] Yes
[X] No
```
> log retrieved user info from idam

- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.preview.template.yaml
- charts/ccd-data-store-api/values.yaml
- liquibase.gradle
- src/main/java/uk/gov/hmcts/ccd/AliasWebConfig.java
- src/main/java/uk/gov/hmcts/ccd/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/data/SecurityUtils.java
- src/main/java/uk/gov/hmcts/ccd/data/user/DefaultUserRepository.java
- src/main/java/uk/gov/hmcts/ccd/security/JwtGrantedAuthoritiesConverter.java
- src/main/java/uk/gov/hmcts/ccd/security/idam/IdamRepository.java
https://tools.hmcts.net/jira/browse/RDM-10390
```
[ ] Yes
[X] No
```
> Resolve conflicts

- build.gradle
**JIRA link (if applicable)**
https://tools.hmcts.net/jira/browse/RDM-10385
Upgrade to latest stable release.
```
[ ] Yes
[X] No
```
> use stable version

- charts/ccd-data-store-api/Chart.yaml
> Update Chart.yaml back to Java 3.4.4

- Jenkinsfile_CNP
- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.preview.template.yaml
- charts/ccd-data-store-api/values.yaml
> adjust min and max replicas

- Jenkinsfile_CNP
> enable es fta on master

- Jenkinsfile_CNP
- dependency-check-suppressions.xml
> change data store develop pr

- src/main/resources/db/changelog/db.changelog-RDM-9910.xml
> splitting sql into different change sets

- src/main/resources/db/changelog/db.changelog-RDM-9910.xml
> Alter column default into multiple statements

- dependency-check-suppressions.xml
> suppress new cves temporarily

- lib/AI-Agent.xml
https://tools.hmcts.net/jira/browse/RDM-10518
changed app-insights Logging threshold to info (default warn)
```
[ ] Yes
[ x] No
```
> changed app-insights Logging threshold to info (default warn)

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-10549
Fix CVEs Newly Reported on All 4 Java Apps
```
[ ] Yes
[X] No
```
> RDM-10549 Fix 2 CVEs Newly Reported on All 4 Java Apps

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseAuditEventEntity.java
https://tools.hmcts.net/jira/browse/RDM-10527
RDM-10527 - Eager fetch SignificantItems to reduce number of DB calls
```
[ ] Yes
[x] No
```
> RDM-10527 - Eager fetch SignificantItems to reduce number of DB calls

- infrastructure/perftest.tfvars
- src/main/resources/db/changelog/db.changelog-RDM-9910.xml
> 20.2 fixes from perftest branch

- build.gradle
> patch concurrent execution of functional tests

- Jenkinsfile_CNP
> correct wiring in pipeline

- src/aat/resources/features/F-106/F-106.feature
- src/aat/resources/features/F-120 supplementary_data in ES Search API/F-120.feature
https://tools.hmcts.net/jira/browse/RDM-10734
Fix Bug in Data Store Develop Branch Breaking the Build
```
[ ] Yes
[X] No
```
> Trigger notification

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDM-10734
Fix Bug in Data Store Develop Branch Breaking the Build
```
[ ] Yes
[X] No
```
> RDM-10734 ignored elastic search tests

- src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/DefaultStartEventOperation.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/DefaultStartEventOperationTest.java
Still need to write new integration tests as none exists atm.
Setting classification for new fields
```
[ ] Yes
[ x] No
```
> Setting classification for new fields

- Jenkinsfile_CNP
> Temporarily disable ES FT on master

- Jenkinsfile_CNP
- build.gradle
- charts/ccd-data-store-api/values.preview.template.yaml
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-10681
fix newly reported CVE's in data store
```
[ ] Yes
[X] No
```
> RDM-10681 fix newly reported CVE's in data store

- Jenkinsfile_CNP
- charts/ccd-data-store-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-10734
Fix Bug in Data Store Develop Branch Breaking the Build - Enable elastic search
```
[ ] Yes
[X] No
```
> RDM-10734 enable elastic search

- Jenkinsfile_CNP
- charts/ccd-data-store-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-10734
Fix Bug in Data Store Develop Branch Breaking the Build
```
[ ] Yes
[X] No
```
> RDM-10734 restore temporary tweaks

- src/aat/resources/features/F-109/S-947.td.json
https://tools.hmcts.net/jira/browse/RDM-10697
Data store API smoke tests are failing
```
[ ] Yes
[X] No
```
> Rdm 10697 develop

- src/aat/resources/features/F-109/S-947.td.json
https://tools.hmcts.net/jira/browse/RDM-10697
Data store API smoke tests are failing
```
[ ] Yes
[X] No
```
> RDM-10697 added unordered in json

- build.gradle
> Fix BEFTA Cucumber reports

- src/aat/resources/features/F-121/S-121.6.td.json
> fix merge error

- src/aat/resources/features/F-121/F-121.feature
- src/aat/resources/features/F-121/S-121.2.td.json
- src/aat/resources/features/F-121/S-121.3.td.json
https://tools.hmcts.net/jira/browse/RDM-9754
Adjust test data for rdm 9754 and format the data file
```
[ ] Yes
[X] No
```
> Adjust test data for rdm 9754

- Jenkinsfile_CNP
- charts/ccd-data-store-api/values.preview.template.yaml
- src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/CoreCaseDataApplication.java
- src/test/java/uk/gov/hmcts/ccd/BaseTest.java
- src/test/java/uk/gov/hmcts/ccd/WireMockBaseTest.java
- src/test/java/uk/gov/hmcts/ccd/data/definition/DefaultCaseDefinitionRepositoryIT.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/stdapi/DocumentsOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointUserRolesIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/SearchWithSortIT.java
- src/test/java/uk/gov/hmcts/ccd/integrations/DefinitionsCachingIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/BaseCaseAssignedUserRolesControllerIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/DocumentControllerITest.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/StartEventControllerCaseRolesIT.java
- src/test/resources/integration_tests.properties
- src/test/resources/test.properties
https://tools.hmcts.net/jira/browse/RDM-10838
Reduce the separate Spring Boot contexts created for integration tests.
```
[ ] Yes
[X] No
```
> RDM-10838 - SpringBootTest app context caching for reduced integration testing time

- src/aat/resources/features/F-028/S-044.td.json
- src/aat/resources/features/F-029/S-049.td.json
- src/aat/resources/features/F-121/S-121.4.td.json
- src/aat/resources/features/F-121/S-121.6.td.json
- src/aat/resources/features/F-121/S-121.7.td.json
> update tests for master 

- infrastructure/prod.tfvars
> Update prod.tfvars increase D/B disk

- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/RDM-10961
Correct disk space value
```
[ ] Yes
[X] No
```
> set to exact value

- src/aat/resources/features/F-104/S-628.td.json
- src/aat/resources/features/F-104/S-638.td.json
- src/aat/resources/features/F-120 supplementary_data in ES Search API/S-120.2.td.json
> Fix test ordering issue on master

- build.gradle
- src/aat/resources/features/F-104/S-638.td.json
> Fix failing test by adding missing retain_hidden_value field

- build.gradle
> Update befta-fw version

- src/aat/resources/features/F-104/S-628.td.json
- src/aat/resources/features/F-104/S-638.td.json
- src/aat/resources/features/F-120 supplementary_data in ES Search API/S-120.2.td.json
- src/aat/resources/features/F-123 - Retain Hidden Value/S-123.1.td.json
RDM-11212
Fix broken build with test data adjustments.
```
[ ] Yes
[X] No
```
> add unordered assertion directives

- src/aat/resources/features/F-104/S-628.td.json
- src/aat/resources/features/F-104/S-638.td.json
- src/aat/resources/features/F-120 supplementary_data in ES Search API/S-120.2.td.json
> Rdm 11212 master fix 2

- dependency-check-suppressions.xml
> cleanup cve suppressions

- src/main/java/uk/gov/hmcts/ccd/domain/model/std/MessageInformation.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
https://tools.hmcts.net/jira/browse/RDM-11155
Align message publishing JSON with scope doc
```
[ ] Yes
[x] No
```
> RDM-11155 - Align IDs to scope doc

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseAuditEventEntity.java
> Fix develop build

- src/aat/resources/features/F-126/F-126.feature
> temporarily ignore test to unblock pipeline

- src/main/resources/db/changelog/db.changelog-RDM-10340-1.xml
- src/main/resources/db/changelog/db.changelog-RDM-10340.xml
- src/main/resources/db/changelog/db.changelog-master.xml
https://tools.hmcts.net/jira/browse/RDM-10738
Resolve modifications to already-released changelog
```
[ ] Yes
[X] No
```
> RDM-10738 Resolve modifications to already-released changelog

- src/aat/resources/features/F-127 - Even Enabling Condition/F-127.feature
- src/aat/resources/features/F-128 - Dynamic Lists/F-128.feature
> Temp disable failing fts

- build.gradle
- src/main/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperation.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperationTest.java
https://tools.hmcts.net/jira/browse/RDM-11213
```
[ ] Yes
[X] No
```
> RDM-11213: Disregard [CREATOR] role

- dependency-check-suppressions.xml
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11088
```
[ ] Yes
[X] No
```
> RDM-11088 Upgrade to Postgres 11 on PerfTest

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11088
```
[ ] Yes
[X] No
```
> Updated dependency-check-suppressions

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11432
CVE-2021-22112 (Data Store)
```
[ ] Yes
[X] No
```
> RDM-11432 CVE-2021-22112 (Data Store) and other CVE's

- src/aat/resources/features/F-027/S-038_Full.td.json
- src/aat/resources/features/F-027/S-590.td.json
- src/aat/resources/features/F-065/S-165.td.json
- src/aat/resources/features/F-104/S-627.td.json
- src/aat/resources/features/F-104/S-629.td.json
- src/aat/resources/features/F-104/S-630.td.json
- src/aat/resources/features/F-104/S-633.td.json
- src/aat/resources/features/F-104/S-634.td.json
- src/aat/resources/features/F-104/S-635.td.json
- src/aat/resources/features/F-104/S-636.td.json
- src/aat/resources/features/F-104/S-637.td.json
- src/aat/resources/features/F-104/S-639.td.json
- src/aat/resources/features/F-104/S-640.td.json
- src/aat/resources/features/F-109/S-945.td.json
- src/aat/resources/features/F-109/S-946.td.json
- src/aat/resources/features/F-109/S-947.td.json
- src/aat/resources/features/F-120 supplementary_data in ES Search API/S-120.3.td.json
- src/aat/resources/features/F-120 supplementary_data in ES Search API/S-120.4.td.json
> Fix failing tests on develop

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-11501
CVE-2021-25122 (Data Store)
```
[ ] Yes
[X] No
```
> RDM-11501 CVE-2021-25122 (Data Store)

- Jenkinsfile_CNP
- charts/ccd-data-store-api/values.preview.template.yaml
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11765
Update CVE Suppress Until Date In All Services
```
[ ] Yes
[X] No
```
> RDM-11765 Update CVE Suppress Until Date In All Services

- Jenkinsfile_CNP
- charts/ccd-data-store-api/values.preview.template.yaml
> revert temporary ci cd arrangement

- src/aat/resources/features/F-051/S-109.td.json
- src/aat/resources/features/F-102/S-580.td.json
> Format test data

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11091
```
[X] Yes
[ ] No
```
> RDM-110901: CCD-DATA-STORE postgres V11 migration

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11091
CCD-DATA-STORE: Upgrade to Postgres 11 on ITHC - clean up old db
```
[ ] Yes
[ X] No
```
> RDM-11091: CCD-DATA-STORE: Upgrade to Postgres 11 on ITHC (clean up old db)

- src/aat/resources/features/F-127 - Even Enabling Condition/F-127.feature
- src/aat/resources/features/F-128 - Dynamic Lists/F-128.feature
This reverts commit df28b3d40119264f8ffba6bbb91eb8231fce4b37.
```
[ ] Yes
[ ] No
```
> Revert "temporarily disable failing tests"

- dependency-check-suppressions.xml
- infrastructure/main.tf
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDM-11582
```
[ ] Yes
[ X] No
```
> RDM-11582: Remove Old DB

- infrastructure/main.tf
> Rdm 11088 postgres11 1: remove old db

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-10969
```
[ ] Yes
[x ] No
```
> RDM-10969: Migrate Data store DB and Logstash for demo env (Demo PR)

- Jenkinsfile_CNP
> TA-82: Disable pact tests

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-10969
Remove old Db
```
[ ] Yes
[ X] No
```
> RDM-10969: remove old db

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-12131
Extend Expiry Dates of All CVE Suppressions in CCD Repos
```
[ ] Yes
[X] No
```
> RDM-12175 Updated chart version

- src/main/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperation.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/AddCaseAssignedUserRolesControllerIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/BaseCaseAssignedUserRolesControllerIT.java
https://tools.hmcts.net/jira/browse/RDM-9354
```
[ ] Yes
[ ] No
```
> RDM-9354 Case Sensitive CaseRole on Add Case-Assigned Users and Roles endpoint

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-9765
Bump up BEFTA Fw version for RDM-9765.
```
[ ] Yes
[X] No
```
> RDM-9765 Added jit pack and befta code changes

- build.gradle
> Suppress old Sonar Warnings

- src/aat/resources/features/F-106/F-106.feature
- src/main/java/uk/gov/hmcts/ccd/domain/model/std/SupplementaryData.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/std/SupplementaryDataTest.java
https://tools.hmcts.net/jira/browse/CCD-992
Code changes added to handle the unknown keys for supplementary data updates
```
[ ] Yes
[x] No
```
> CCD-992: Fix Intermittent Supplementary Data Failures

- src/contractTest/resources/application.properties
https://tools.hmcts.net/jira/browse/CCD-1017
remove sensitive information from repo
```
[ ] Yes
[X] No
```
> CCD-1017 remove sensitive information from repo

- src/aat/resources/features/F-101/F-101.feature
- src/aat/resources/features/F-105 - Add Case-Assigned Users and Roles/F-105.feature
- src/aat/resources/features/F-106/F-106.feature
- src/aat/resources/features/F-107/F-107.feature
NA
Ignored the FT tests that are failing intermittently
```
[ ] Yes
[x] No
```
> Ignore the FT tests that are failing intermittently

- src/main/java/uk/gov/hmcts/ccd/data/caseaccess/CachedCaseUserRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/caseaccess/CaseUserEntity.java
- src/main/java/uk/gov/hmcts/ccd/data/caseaccess/CaseUserRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/caseaccess/DefaultCaseUserRepository.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/AuthorisedSearchOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/security/DefaultAuthorisedCaseDefinitionDataService.java
- src/test/java/uk/gov/hmcts/ccd/data/caseaccess/CachedCaseUserRepositoryTest.java
- src/test/java/uk/gov/hmcts/ccd/data/caseaccess/DefaultCaseUserRepositoryTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/DefaultAuthorisedCaseDefinitionDataServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/AuthorisedSearchOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseSearchEndpointESSecurityIT.java
- src/test/resources/elasticsearch/data/security_cases/security-case-04.json
- src/test/resources/mappings/security-case-type-1.json
- src/test/resources/sql/insert_case_users.sql
- src/test/resources/sql/insert_elasticsearch_cases.sql
https://tools.hmcts.net/jira/browse/CCD-1025
Fix for the Case Search functionality to address the Case Roles capability.
```
[ ] Yes
[X] No
```
> Ccd 1025 data store

- src/aat/java/uk/gov/hmcts/ccd/datastore/befta/DataStoreTestAutomationAdapter.java
- src/aat/resources/features/F-105 - Add Case-Assigned Users and Roles/F-105.feature
- src/aat/resources/features/F-106/F-106.feature
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/supplementarydata/DefaultSupplementaryDataRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/supplementarydata/IncrementSupplementaryDataQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/supplementarydata/SetSupplementaryDataQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/std/SupplementaryData.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/supplementarydata/DefaultSupplementaryDataUpdateOperation.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/std/SupplementaryDataTest.java
https://tools.hmcts.net/jira/browse/CCD-992
Fixed intermittent functional test failures
```
[ ] Yes
[x] No
```
> CCD-992: Fix intermittent functional test failures

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/supplementarydata/DefaultSupplementaryDataRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/supplementarydata/SupplementaryDataQueryBuilder.java
- src/test/java/uk/gov/hmcts/ccd/data/casedetails/supplementarydata/SetSupplementaryDataQueryBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/std/SupplementaryDataTest.java
https://tools.hmcts.net/jira/browse/CCD-992
Closed all review comments
```
[ ] Yes
[x] No
```
> CCD-992: Close review comments

- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetUserProfileOperation.java
- src/main/java/uk/gov/hmcts/ccd/v2/internal/resource/JurisdictionViewResource.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetUserProfileOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/UserProfileEndpointTest.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UIDefinitionControllerIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UIUserProfileControllerIT.java
- src/test/resources/mappings/jurisdiction_test.json
- src/test/resources/sql/insert_case_users.sql
https://tools.hmcts.net/jira/browse/CCD-1026
CCD / ExUI: Integrate "Default State" Workbasket Input Filters with CaseRoles Permissions
```
[ ] Yes
[X] No
```
> CCD-1026 CCD / ExUI: Integrate "Default State" Workbasket Input Filter with CaseRoles Permissions

- infrastructure/aat.tfvars
- infrastructure/prod.tfvars
> Increase DB sizes (without autogrow)

- Jenkinsfile_CNP
- charts/ccd-data-store-api/values.preview.template.yaml
> update user profile develop pr

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1228
CVE-2021-22112 (CCD Data Store API)
```
[ ] Yes
[x] No
```
> CCD-1228 CVE-2021-22112 (CCD Data Store API)

- charts/ccd-data-store-api/values.aat.template.yaml
- infrastructure/main.tf
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDM-11097
```
[X ] Yes
[ ] No
```
> RDM-11097: remove old db

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-1223
use befta fw and ccd definitions from separate artefacts
```
[ ] Yes
[x] No
```
> move befta test definitions to their new repo

- src/aat/java/uk/gov/hmcts/ccd/datastore/befta/DataStoreTestAutomationAdapter.java
https://tools.hmcts.net/jira/browse/CCD-1223
update valid def resorce path
```
[ ] Yes
[X] No
```
> change resource path of valid ccd test definitions

- src/aat/resources/features/F-101/F-101.feature
- src/aat/resources/features/F-107/F-107.feature
- src/main/java/uk/gov/hmcts/ccd/domain/types/BaseType.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/BaseTypeTest.java
https://tools.hmcts.net/jira/browse/CCD-1122
Fix for intermittent FT issues
```
[ ] Yes
[x] No
```
> CCD-1122: Intermittent issue fix

- build.gradle
- src/aat/resources/features/F-028/S-044.td.json
- src/aat/resources/features/F-066/S-182.td.json
> bump befta version for adapted test

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1263
CVE-2021-22118 in CCD Data Store API
```
[ ] Yes
[x] No
```
> CCD-1263 CVE-2021-22118 in CCD Data Store API

- build.gradle
- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/AccessControlList.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/RoleToAccessProfileDefinition.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/CaseDataAccessControl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AttributeBasedAccessControlService.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/definition/AccessControlListTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControlTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AttributeBasedAccessControlServiceTest.java
https://tools.hmcts.net/jira/browse/RDM-12540
```
[ ] Yes
[ X] No
```
> RDM-12540: Fix json issue on access control list

- src/main/java/uk/gov/hmcts/ccd/auditlog/AuditInterceptor.java
- src/test/java/uk/gov/hmcts/ccd/auditlog/AuditInterceptorTest.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerTestIT.java
https://tools.hmcts.net/jira/browse/CCD-1108
Fix Unnecessary Error Logs after CCD-107 and CCD-127
```
[ ] Yes
[x] No
```
> CCD-1108 Fix Unnecessary Error Logs after CCD-107 and CCD-127

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1263
CVE-2021-22118 in CCD Data Store API
```
[ ] Yes
[x] No
```
> CCD-1263 CVE-2021-22118 in CCD Data Store API refactored

- src/main/resources/db/migration/V20210608__CCD-1249_add_index_hearingVenue.sql
https://tools.hmcts.net/jira/browse/CCD-1249
```
[ ] Yes
[X] No
```
> CCD-1249 : Creating a new index for hearingVenue

- src/main/resources/db/migration/V20210608_1249__CCD-1249_add_index_hearingVenue.sql
- src/main/resources/db/migration/V20210608__CCD-1249_add_index_hearingVenue.sql
https://tools.hmcts.net/jira/browse/CCD-1291
Created index with concurrently keyword
```
[ ] Yes
[x] No
```
> CCD-1291: data-store staging deployment failure in AAT

- src/aat/java/uk/gov/hmcts/ccd/datastore/befta/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/CCD-1284
tolerate data setup failures on pipelines
```
[ ] Yes
[X] No
```
> tolerate data setup failures

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-1131
befta-fw update to 8.2.0
```
[ ] Yes
[x] No
```
> befta-fw update to 8.2.0

- src/main/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/RoleAssignmentAttributesResource.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/RoleAssignment.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/RoleAssignmentAttributes.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/AuthorisationsMatcher.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/BeginDateEndDateMatcher.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/CaseTypeMatcher.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/GrantTypeMatcher.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/RoleAttributeMatcher.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/RoleNameMatcher.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleAssignmentService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleAssignmentsMapperImpl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/ElasticsearchUserCaseAccessFilter.java
- src/test/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/RoleAssignmentResourceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/AuthorisationsMatcherTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/GrantTypeMatcherTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/RoleNameMatcherTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/accessprofile/filter/BaseFilter.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControlTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleAssignmentServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleAssignmentsMapperTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/ElasticsearchUserCaseAccessFilterTest.java
…Search
https://tools.hmcts.net/jira/browse/RDM-11981
Update role assignments filtering before executing the search query in ES.
```
[ ] Yes
[X ] No
```
> RDM-11981 Filtering Role Assignments that apply for a CaseType for

- src/test/resources/mappings/base-types.json
https://tools.hmcts.net/jira/browse/CCD-142
Added DynamicMultiSelectList and DynamicRadioList field types to base-types stub
```
[ ] Yes
[x] No
```
> CCD-142: Fix Flaky Data Store Test

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1563
```
[ ] Yes
[ ] No
```
> suppress CVE

- build.gradle
> Update ccd-test-definitions to v7.2.0

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1563
fix for CVE-2021-27568
```
[ ] Yes
[x] No
```
> fix for CVE-2021-27568

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1638
fix for CVE-2021-33037
```
[ ] Yes
[ ] No
```
> fix for CVE-2021-33037

- build.gradle
- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/data/SecurityUtils.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/search/CaseDocumentsMetadata.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentAmApiClient.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentMetadataMapper.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/hmcts/ccd/WireMockBaseTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentAmApiClientTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentMetadataMapperTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentServiceTest.java
- src/test/resources/test.properties
https://github.com/hmcts/ccd-case-document-am-client/pull/21
```
[ ] Yes
[X] No
```
> Rdm 12672 - Use case-doc-am-client in CCD Data Store

- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.yaml
- src/main/resources/application.properties
- src/test/resources/test.properties
> CCD-1662 - Separate IDAM_USER_URL into IDAM_API_BASE_URL and IDAM_OIDC_URL

- src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/CasesControllerProviderTest.java
- src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/caseassigned/CaseAssignedUserRolesProviderTest.java
> Change PACT version selector

- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/CCD-1667
Fortify integration
```
[ ] Yes
[ ] No
```
> Fortify integration

- charts/ccd-data-store-api/Chart.yaml
- src/aat/resources/features/F-044 - Submit Event V1 External/S-579-Update_Case_For_Solicitor_Data_Base.td.json
- src/aat/resources/features/F-044 - Submit Event V1 External/S-579.td.json
- src/aat/resources/features/common/case_document/Common_Response_Body_Document_Base.td.json
- src/contractTest/resources/application.properties
https://tools.hmcts.net/jira/browse/RDM-12710
Add missing fields:
- createdBy
- lastModifiedBy
- modifiedOn
```
[ ] Yes
[x] No
```
> RDM-12710 Add missing upload response fields

- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/data/draft/DefaultDraftGateway.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/draft/DraftResponse.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/std/DraftsEndpoint.java
- src/test/java/uk/gov/hmcts/ccd/data/draft/DefaultDraftGatewayTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/DraftsEndpointIT.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/DraftsEndpointTest.java
https://tools.hmcts.net/jira/browse/CCD-1281
Draft ID validation has been removed and Sonar issues fixed
```
[ ] Yes
[x] No
```
> CCD:1281 - Remove Draft ID validation

- src/main/java/uk/gov/hmcts/ccd/domain/model/search/elasticsearch/ElasticsearchRequest.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/CaseSearchRequest.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/ElasticsearchCaseSearchOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/AuthorisedCaseSearchOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/CaseSearchRequestSecurity.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/ElasticsearchCaseSearchRequestSecurity.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/search/elasticsearch/ElasticsearchRequestTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/CaseSearchRequestTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/CrossCaseTypeSearchRequestTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/ElasticsearchCaseSearchOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/ElasticsearchQueryHelperTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/AuthorisedCaseSearchOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/ElasticsearchCaseSearchRequestSecurityTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseSearchEndpointTest.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UICaseSearchControllerTest.java
> Rdm 12700 patch

- dependency-check-suppressions.xml
Suppress CVE-2021-22144
```
[ ] Yes
[x] No
```
> Suppress CVE-2021-22144

- src/main/resources/db/migration/V20210810_1227__CCD-1227_analyse_arrange_required_indexes_data_store.sql
https://tools.hmcts.net/jira/browse/CCD-1227
```
[ ] Yes
[X] No
```
> CCD-1227 : New indices for slow queries.

- dependency-check-suppressions.xml
> supppres cve flag

- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentUtils.java
- src/test/resources/tests/case-data.json
> excluding hearing doc nodes for metadata processing.

- Jenkinsfile_nightly
Added missing env variable for CASE_DOCUMENT_AM_URL
```
[ ] Yes
[x] No
```
> CCD-1833 Added missing env variable

- dependency-check-suppressions.xml
Suppress CVE-2021-28170
```
[ ] Yes
[x] No
```
> Suppress CVE-2021-28170

- .travis.yml
- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1827
```
[ ] Yes
[x] No
```
> CCD-1827 remove Codacy

- src/contractTest/resources/application.properties
- src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepository.java
- src/main/resources/application.properties
- src/test/java/uk/gov/hmcts/ccd/BaseTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackInvokerWireMockTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointUserRolesIT.java
- src/test/resources/test.properties
> CCD-913: Added request scope persistence for jurisdiction cache

- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleAssignmentCategoryService.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleAssignmentCategoryServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/AddCaseAssignedUserRolesControllerIT.java
> RDM-12745 - Default role category to CITIZEN

- dependency-check-suppressions.xml
Suppress CVE-2020-23171
```
[ ] Yes
[x] No
```
> Suppress CVE-2020-23171

- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/CCD-1876 
double storage for higher iops
```
[ ] Yes
[X] No
```
> double storage for higher iops

- src/main/java/uk/gov/hmcts/ccd/data/user/AttributeBasedJurisdictionsResolver.java
- src/test/java/uk/gov/hmcts/ccd/data/user/AttributeBasedJurisdictionsResolverTest.java
https://tools.hmcts.net/jira/browse/RDM-12758
```
[ ] Yes
[ ] No
```
> RDM-12578 filter user roles

- src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseDataService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationUtils.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityValidationService.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseDataServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationServiceTest.java
https://tools.hmcts.net/jira/browse/CCD-1895
Revert the changes
```
[ ] Yes
[x] No
```
> CCD-322: Revert

- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/ElasticsearchCaseSearchRequestSecurityTest.java
https://tools.hmcts.net/jira/browse/RDM-12768
An update to a test to assert the full query
```
[ ] Yes
[x] No
```
> Rdm 12768 - update unit tests

- src/test/java/uk/gov/hmcts/ccd/data/ReferenceDataCacheRefreshIT.java
N/A
Resolve intermittent failure of `testThatExceptionShouldNotDisableCacheRefreshScheduler()`
```
[ ] Yes
[x] No
```
> NOJIRA Resolve intermittent test failure

- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseDetailsEntity.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseDetailsMapper.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetails.java
- src/main/resources/db/migration/V20210921_12840__RDM_12840_add_resolved_ttl_to_case_data.sql
- src/test/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepositoryTest.java
https://tools.hmcts.net/jira/browse/RDM-12840
Add new `resolved_ttl` column to `case_data` table and update relevant entity, mapper and tests accordingly
```
[ ] Yes
[X] No
```
> RDM-12840 - Add Resolved TimeToLive metadata to case data

- infrastructure/aat.tfvars
update storage MB as per the manually improved amount
```
[ ] Yes
[x] No
```
> update storage MB as per the manually improved amount

- infrastructure/aat.tfvars
> update storage MD as per the manually improved amount

- dependency-check-suppressions.xml
> extend until dates

- dependency-check-suppressions.xml
- infrastructure/aat.tfvars
- infrastructure/state.tf
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/PseudoRoleAssignmentsGenerator.java
> Filter non-null user roles for pseudo role assignment generation

- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/CaseDataAccessControl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/PseudoRoleAssignmentsGenerator.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleBasedCaseDataAccessControl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AttributeBasedSecurityClassificationService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/SubmitCaseTransaction.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControlTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/PseudoRoleAssignmentsGeneratorTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleBasedCaseDataAccessControlTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AttributeBasedSecurityClassificationServiceTest.java
https://tools.hmcts.net/jira/browse/RDM-12864
Resolve pseudo role assignment generation and SC related issues for citizen case creation
```
[ ] Yes
[x] No
```
> RDM-12864 - Resolve pseudo role assignment generation and SC related issues for citizen case creation

- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceTest.java
https://tools.hmcts.net/jira/browse/CCD-2007
Respondent Sols not seeing their unassigned case list
```
[ ] Yes
[x] No
```
> Cfts 1020 master 2

- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/AccessControlGrantTypeESQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/BasicGrantTypeESQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/ChallengedGrantTypeESQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/ExcludedGrantTypeESQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/GrantTypeESQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/SpecificGrantTypeESQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/StandardGrantTypeESQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/ElasticsearchCaseSearchRequestSecurity.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/AccessControlGrantTypeESQueryBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/BasicGrantTypeESQueryBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/ChallengedGrantTypeESQueryBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/ExcludedGrantTypeESQueryBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/SpecificGrantTypeESQueryBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/StandardGrantTypeESQueryBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/ElasticsearchCaseSearchRequestSecurityTest.java
> RDM-12928 - Refactor to use common code aligning with latest FS

- src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/RoleAssignment.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/PseudoRoleAssignmentsGenerator.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/PseudoRoleAssignmentsGeneratorTest.java
> Filter out EXCLUDED role assignments in pseudo generation for granted users

- infrastructure/aat.tfvars
https://tools.hmcts.net/jira/browse/CCD-2146
scaleup-data-store-db-storage-in-aat
```
[ ] Yes
[X] No
```
> scaleup storage

- src/contractTest/resources/application.properties
- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CommonField.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceFilterTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceTest.java
https://tools.hmcts.net/jira/browse/CCD-2130 and
https://tools.hmcts.net/jira/browse/CCD-2129
Hide the fields in UI if the user don't have read access
```
[ ] Yes
[x] No
```
> CCD-2130 and CCD-2129

- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/global/GlobalSearchQueryBuilder.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/global/GlobalSearchQueryBuilderTest.java
https://tools.hmcts.net/jira/browse/RDM-12906
```
[ ] Yes
[X] No
```
> RDM-12906: Implementation of wildcard search for some fields

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/AccessControlGrantTypeQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/BasicGrantTypeQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/ChallengedGrantTypeQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/ExcludedGrantTypeQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/GrantTypeQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/GrantTypeSqlQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/SpecificGrantTypeQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/StandardGrantTypeQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/AuthorisationsMatcher.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/AuthorisationMapper.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/SearchRoleAssignment.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/ExcludedGrantTypeESQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/GrantTypeESQueryBuilder.java
- src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/AccessControlGrantTypeQueryBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/BasicGrantTypeQueryBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/ChallengedGrantTypeQueryBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/AccessProfileServiceImplTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/AuthorisationsMatcherTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControlTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/AccessControlGrantTypeESQueryBuilderTest.java
> RDM-12950 - Group role assignments for building search queries

- src/main/java/uk/gov/hmcts/ccd/domain/service/security/DefaultAuthorisedCaseDefinitionDataService.java
- src/test/java/uk/gov/hmcts/ccd/ElasticsearchIT.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/DefaultAuthorisedCaseDefinitionDataServiceTest.java
https://tools.hmcts.net/jira/browse/RDM-12959
```
[ ] Yes
[X ] No
```
> RDM-12959: Remove Classification check against Jurisdiction in ES

- src/main/java/uk/gov/hmcts/ccd/domain/service/search/AuthorisedSearchOperation.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/AuthorisedSearchOperationTest.java
https://tools.hmcts.net/jira/browse/RDM-12969
```
[ ] Yes
[ X] No
```
> RDM-12969: [AC] Incorrect (SQL) Search result for caseType higher than PUBLIC

- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/CachedCaseDataAccessControlImpl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/CaseDataAccessControl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/NoCacheCaseDataAccessControl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleBasedCaseDataAccessControl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationServiceImpl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/security/DefaultAuthorisedCaseDefinitionDataService.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/DefaultAuthorisedCaseDefinitionDataServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationServiceTest.java
> RDM-12954 - Get user classifications depending on whether creation flow

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/GrantTypeQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/GrantTypeSqlQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/SearchRoleAssignment.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/GrantTypeESQueryBuilder.java
… getReadableStates calls
```
[ ] Yes
[ ] No
```
> RDM-12960 - Group by role name in search to reduce number of calls

- Jenkinsfile_nightly
CCD-2154 (https://tools.hmcts.net/jira/browse/CCD-2154)
- Added BEFTA_S2S_CLIENT_SECRET_OF_XUI_WEBAPP entry to s2s secrets section in Jenkinsfile_nightly.  This is needed for functional tests.
```
[ ] Yes
[x] No
```
> CCD-2154: Fix functional test failure in nightly build

- src/main/java/uk/gov/hmcts/ccd/domain/service/processor/GlobalSearchProcessorService.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/processor/GlobalSearchProcessorServiceTest.java
[RDM-12895](https://tools.hmcts.net/jira/browse/RDM-12895) _"[Global Search] Not able to search cases that don't have certain fields "_
GlobalSearchProcessorService.populateGlobalSearchData: always output data with 'SearchCriteria' field even if empty; as it is used by logstash process as a trigger to tell it to send case data to the Global Search index.
```
[ ] Yes
[x] No
```
> RDM-12895 always populate SearchCriteria if GS configured

- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/CachedCaseDataAccessControlImpl.java
> CFTS-1587 - Don't cache SC when case reference does not exist (Legacy cases)

- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/CachedCaseDataAccessControlImpl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/CaseSearchResultViewGenerator.java
https://tools.hmcts.net/jira/browse/CCD-2282
Fix for CCD-2282
```
[ ] Yes
[X] No
```
> Default case metadata for search with "psuedo" case records

- src/contractTest/resources/application.properties
- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceImpl.java
- src/main/resources/application.properties
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceTest.java
https://tools.hmcts.net/jira/browse/CCD-2240
Tactical fix for Multiparty Event
```
[ ] Yes
[x] No
```
> CCD-2240: Tactical fix for Multiparty Event

- src/aat/resources/features/F-065 - Get Case V2 Internal/F-065.feature
- src/aat/resources/features/F-134 - AC CRUD internal jurisdictions/F-134.feature
> Four test scenarios were flagged with @Ignore

- charts/ccd-data-store-api/values.preview.template.yaml
> updated environment endpoints

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-2333
```
[ ] Yes
[ ] No
```
> update log4j version to 2.15.0

- src/aat/resources/features/F-126 - Get Case Events On Behalf Of User/F-126.feature
- src/aat/resources/features/F-129 - Access Control SC/F-129.feature
- src/aat/resources/features/F-136 - AC CRUD internal work-basket-inputs/F-136.feature
- src/aat/resources/features/F-137 - AC CRUD internal search-inputs/F-137.feature
- src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepository.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/PseudoRoleToAccessProfileGenerator.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControlTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/PseudoRoleToAccessProfileGeneratorTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
- src/test/resources/mappings/case-type-definition-probate-GrantOfRepresentation.json
- src/test/resources/mappings/jurisdiction_probate.json
- src/test/resources/mappings/messagepublishing-definition.json
#1763 and #1764 combined in single PR
```
[ ] Yes
[x] No
```
> CCD-2343 and CCD-2346 combined

- src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/PseudoRoleToAccessProfileGenerator.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControlTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/PseudoRoleToAccessProfileGeneratorTest.java
- src/test/resources/mappings/case-type-definition-probate-GrantOfRepresentation.json
- src/test/resources/mappings/jurisdiction_probate.json
- src/test/resources/mappings/messagepublishing-definition.json
https://tools.hmcts.net/jira/browse/CCD-2346
Cache pseudo RoleToAccessProfiles by case type version
```
[ ] Yes
[x] No
```
> CCD-2346 - Cache pseudo RoleToAccessProfiles by case type version

- src/aat/resources/features/F-126 - Get Case Events On Behalf Of User/F-126.feature
- src/aat/resources/features/F-129 - Access Control SC/F-129.feature
- src/aat/resources/features/F-136 - AC CRUD internal work-basket-inputs/F-136.feature
- src/aat/resources/features/F-137 - AC CRUD internal search-inputs/F-137.feature
- src/main/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepository.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
https://tools.hmcts.net/jira/browse/CCD-2343
Request scope caching improvement for CaseDefinitionRepository
```
[ ] Yes
[x] No
```
> CCD-2343: Request scope caching improvement for CaseDefinitionRepository

- src/aat/resources/features/F-126 - Get Case Events On Behalf Of User/F-126.feature
- src/aat/resources/features/F-129 - Access Control SC/F-129.feature
- src/aat/resources/features/F-136 - AC CRUD internal work-basket-inputs/F-136.feature
- src/aat/resources/features/F-137 - AC CRUD internal search-inputs/F-137.feature
- src/main/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepository.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
Reverts hmcts/ccd-data-store-api#1764
> Revert "CCD-2343: Request scope caching improvement for CaseDefinitionRepository"

- src/aat/resources/features/F-053 - Create Case Citizen V1 External/F-053.feature
https://tools.hmcts.net/jira/browse/CCD-1009
```
[ ] Yes
[ ] No
```
> removed @Ignore from @S-552

- src/aat/resources/features/F-126 - Get Case Events On Behalf Of User/F-126.feature
- src/aat/resources/features/F-129 - Access Control SC/F-129.feature
- src/aat/resources/features/F-136 - AC CRUD internal work-basket-inputs/F-136.feature
- src/aat/resources/features/F-137 - AC CRUD internal search-inputs/F-137.feature
- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepository.java
- src/main/resources/application.properties
- src/test/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepositoryTest.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
https://tools.hmcts.net/jira/browse/CCD-2343
Re-introduce CCD-2343 with Feature Toggle
```
[ ] Yes
[X] No
```
> Re-introduce CCD-2343 with Feature Toggle

- src/aat/resources/features/F-126 - Get Case Events On Behalf Of User/F-126.feature
- src/aat/resources/features/F-129 - Access Control SC/F-129.feature
- src/aat/resources/features/F-136 - AC CRUD internal work-basket-inputs/F-136.feature
- src/aat/resources/features/F-137 - AC CRUD internal search-inputs/F-137.feature
- src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
https://tools.hmcts.net/jira/browse/CCD-2350
Fixed
```
[ ] Yes
[x] No
```
> CCD-2350: Fix the ignored tests as part of CCD-2343

- build.gradle
[RDM-12677](https://tools.hmcts.net/jira/browse/RDM-12677) _"Global Search (epic)"_
Build against the next `ccd-test-definitions` pre-release, see hmcts/ccd-test-definitions#28.
```
[ ] Yes
[x] No
```
> RDM-12677 ccd-test-definitions pre-release

- src/contractTest/resources/application.properties
- src/main/java/uk/gov/hmcts/ccd/data/ReferenceDataRepository.java
- src/main/resources/application.properties
[RDM-13073](https://tools.hmcts.net/jira/browse/RDM-13073)
Adjust Reference Data Cache schedule so that it is refreshed daily.
```
[ ] Yes
[x] No
```
> RDM-13073 Adjust Reference Data Cache schedule

- Jenkinsfile_CNP
[RDM-12677](https://tools.hmcts.net/jira/browse/RDM-12677) _"Global Search"_ (epc)
Global Search jenkins / FTA patch
```
[ ] Yes
[x] No
```
> RDM-12677 global_search FTA patch

- src/aat/resources/features/F-1005 - GlobalSearch - Search cases/F-1005.feature
CCD-2465 (https://tools.hmcts.net/jira/browse/CCD-2465)
Temporarily disable F-1005 tests until issues with them are resolved.
```
[ ] Yes
[x] No
```
> CCD-2465: Temporarily disable F-1005 tests

- Jenkinsfile_CNP
- build.gradle
https://tools.hmcts.net/jira/browse/CCD-2457
Publish PACT
```
[ ] Yes
[x] No
```
> CCD-2457: PACT tests failing against CCD consumer

- Jenkinsfile_CNP
Reverts hmcts/ccd-data-store-api#1807
> Revert "CCD-2457: PACT tests failing against CCD consumer"

- infrastructure/prod.tfvars
Scale up Data Store DB.
```
[ ] Yes
[ ] No
```
> scaleup data store db

- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/CCD-2505
Undo temporary upscale of data store DB
```
[ ] Yes
[X] No
```
> [Merge only after 11pm!!] downscale DB back to level before

- src/aat/resources/features/F-131 - Get Event Trigger for Case V2 External/S-1311.td.json
> RDM-12981: Fix issue with new fields

- src/main/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/DefaultRoleAssignmentRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/DefaultCaseDefinitionRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/HttpUIDefinitionGateway.java
- src/main/java/uk/gov/hmcts/ccd/data/user/DefaultUserRepository.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/common/HttpError.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentAmApiClient.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/stdapi/DocumentsOperation.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/exceptions/RestExceptionHandler.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/exceptions/RestExceptionHandlerTest.java
Reverts hmcts/ccd-data-store-api#1800
> Revert "implemented http5xx error handling for rest template and feign client"

- Jenkinsfile_nightly
CCD-2548 (https://tools.hmcts.net/jira/browse/CCD-2548)
Added secrets and variables to Jenkinsfile_nightly file required as a result of updating project to use BEFTA framework 8.7.1.
```
[ ] Yes
[x] No
```
> CCD-2548: Added secrets and variables to Jenkinsfile_nightly

- src/main/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/DefaultRoleAssignmentRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/DefaultCaseDefinitionRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/HttpUIDefinitionGateway.java
- src/main/java/uk/gov/hmcts/ccd/data/user/DefaultUserRepository.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/common/HttpError.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentAmApiClient.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/stdapi/DocumentsOperation.java
- src/main/java/uk/gov/hmcts/ccd/endpoint/exceptions/RestExceptionHandler.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/exceptions/RestExceptionHandlerTest.java
> RDM-2433 into Release 25.1

- build.gradle
- src/aat/resources/features/F-13010 - AC Case Access Categories/CreateCases/F-13010.1_CreateCase.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/CreateCases/F-13010.2_CreateCase.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/CreateCases/F-13010_CreateCase.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/CreateCases/F-13010_CreateCaseBase.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/Events/F-13010_CreateCase_Token_Creation.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/Events/F-13010_Get_Event_Token_Base.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/F-13010.feature
- src/aat/resources/features/F-13010 - AC Case Access Categories/F-13010_CreateCase_Token_Creation.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.1.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.2.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.3.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.4.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.5.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.9.1.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.9.2.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.9.3.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.9.4.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.9.5.td.json
> Rdm 13010: Functional test cases added

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseDetailsEntity.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/GrantTypeQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/GrantTypeSqlQueryBuilder.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/GrantTypeESQueryBuilder.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/BasicGrantTypeESQueryBuilderTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/GrantTypeESQueryBuilderTest.java
https://tools.hmcts.net/jira/browse/RDM-13034
```
[ ] Yes
[ X] No
```
> RDM-13034: Enhance ES Search for Case Access Category

- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlService.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceTest.java
Reverts hmcts/ccd-data-store-api#1852
> Revert "Add CCD -2153(2129/2130) into Release v25.1"

- src/aat/java/uk/gov/hmcts/ccd/datastore/befta/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/CCD-2547
Add Locale Comparison
- Fortify Issue 24154784
- S1858: Remove toString
```
[ ] Yes
[ x] No
```
> Add Locale Comparison

- src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/AuthorisationsMatcher.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/AuthorisationMapper.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/AccessProfileServiceImpl.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/AccessProfileServiceImplTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/AuthorisationsMatcherTest.java
https://tools.hmcts.net/jira/browse/RDM-13111
```
[ ] Yes
[X] No
```
> RDM-13111 Check and update RoleName-CaseType validation during Get/Search/Update operations

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2624
https://tools.hmcts.net/jira/browse/CCD-2611
https://tools.hmcts.net/jira/browse/CCD-2637
https://tools.hmcts.net/jira/browse/CCD-2585
CVE-2021-22060, CVE-2022-23181, CVE-2021-42550, CVE-2021-44832
```
[ ] Yes
[X ] No
```
> CVE fixes data store

- charts/ccd-data-store-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```
> Upgrade to Latest Base Helm Charts

- build.gradle
- src/aat/resources/features/F-1004 - GlobalSearch - Create and update cases/Befta_Global_Search_Case_Data.td.json
- src/aat/resources/features/F-1004 - GlobalSearch - Create and update cases/Befta_Global_Search_Data_Classifications.td.json
- src/aat/resources/features/F-1004 - GlobalSearch - Create and update cases/Befta_Global_Search_Expected_Search_Criteria.td.json
- src/aat/resources/features/F-1004 - GlobalSearch - Create and update cases/Befta_Global_Search_Expected_Updated_Search_Criteria.td.json
This amends the names of the DOD and DOB variables to the new ones used in the definition file.
```
[ ] Yes
[X] No
```
> Amending DOD and DOB variable names for F-1004

- dependency-check-suppressions.xml
One Date amendement was missed in last set of Changes, this is to amend it
https://tools.hmcts.net/jira/browse/CCD-2497
Date Change was missed out and will be corrected
```
[ ] Yes
[ X] No
```
> Fix Suppression Date

- build.gradle
- src/aat/resources/features/F-13010 - AC Case Access Categories/CreateCases/F-13010.1_CreateCase.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/CreateCases/F-13010.2_CreateCase.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/CreateCases/F-13010.3_CreateCase.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/CreateCases/F-13010.4_CreateCase.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/CreateCases/F-13010_CreateCaseBase.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/Events/F-13010.3_CreateCase_Token_Creation.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/Events/F-13010.4_CreateCase_Token_Creation.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/Events/F-13010_Get_Event_Token_Base.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/F-13010.feature
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.1.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.2.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.3.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.4.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.5.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.9.1.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.9.2.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.9.3.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.9.4.td.json
- src/aat/resources/features/F-13010 - AC Case Access Categories/S-13010.9.5.td.json
> Rdm 13033: fixing Functional tests

- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessCategoriesService.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationServiceImpl.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/AuthorisedCreateEventOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/ClassifiedCreateEventOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/CreateCaseEventService.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessCategoriesServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/createevent/AuthorisedCreateEventOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/createevent/ClassifiedCreateEventOperationTest.java
> Rdm 13033 auth

- src/aat/resources/features/F-1005 - GlobalSearch - Search cases/F-1005.feature
- src/aat/resources/features/F-1006 - GlobalSearch - AC tests/F-1006.feature
> Disable GS FTAs

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2790
Suppressing CVE-2022-0265
```
[ ] Yes
[ X] No
```
> Suppressing CVE-2022-0265

- src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/CasesControllerProviderTest.java
- src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/caseassigned/CaseAssignedUserRolesProviderTest.java
https://tools.hmcts.net/jira/browse/CCD-2457
temp disable all state implementations
```
[ ] Yes
[x] No
```
> temp disable all state implementations

- src/main/java/uk/gov/hmcts/ccd/endpoint/exceptions/RestExceptionHandler.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/exceptions/RestExceptionHandlerTest.java
https://tools.hmcts.net/jira/browse/CCD-2809
```
[ ] Yes
[ ] No
```
> implementation of http client status code handling

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-2895
bump up spring fw version
```
[ ] Yes
[X] No
```
> bump up spring fw version

- Jenkinsfile_CNP
- infrastructure/prod.tfvars
> temp disable pact tests

- dependency-check-suppressions.xml
> Temporary suppression

- dependency-check-suppressions.xml
There are several dependency check failures, this change is suppressing them.
```
[ ] Yes
[ x] No
```
> Dependency check failure suppressions

- src/main/resources/db/migration/V20220420_2571__CCD-2571_new_indexes_for_case_data.sql
https://tools.hmcts.net/jira/browse/CCD-2571
```
[ ] Yes
[X] No
```
> added new indexes to case_data

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2893
Vulnerability fix
```
[ ] Yes
[X] No
```
> CCD-2893: Postgres vulnerability issue fix with 42.3.2

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-2779
Bumped ccd-test-definitions version to 7.18.0
```
[ ] Yes
[x] No
```
> Upgrade ccd-test-definitions version to 7.18.0

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3148
```
[ ] Yes
[x ] No
```
> packate update for CVE-2022-25647

- Jenkinsfile_CNP
- src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/caseassigned/CaseAssignedUserRolesProviderTest.java
https://tools.hmcts.net/jira/browse/CCD-2457
```
[ ] Yes
[ ] No
```
> enabled Pact stage

- src/main/java/uk/gov/hmcts/ccd/endpoint/exceptions/RestExceptionHandler.java
- src/test/java/uk/gov/hmcts/ccd/endpoint/exceptions/RestExceptionHandlerTest.java
https://tools.hmcts.net/jira/browse/CCD-2983
```
[ ] Yes
[ ] No
```
> implementation of http client status code handling for IDAM errors

- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/domain/types/DynamicListValidator.java
https://tools.hmcts.net/jira/browse/CCD-3204
CCD-3204 - Added null check to satisfy Fortify warning
```
[ ] Yes
[X] No
```
> CCD-3204 - Added null check to satisfy Fortify warning

- src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/CasesControllerProviderTest.java
https://tools.hmcts.net/jira/browse/CCD-2457
```
[ ] Yes
[ ] No
```
> temp disabled pact tests

- Jenkinsfile_CNP
- charts/ccd-data-store-api/values.preview.template.yaml
- src/aat/resources/features/F-109 - caseworker-caa Authorisation/S-946.td.json
Patch FTA scenario as part of release 26.1
```
[ ] Yes
[x] No
```
> 26.1 patch (develop)

- Jenkinsfile_CNP
- charts/ccd-data-store-api/values.preview.template.yaml
- src/aat/resources/features/F-109 - caseworker-caa Authorisation/S-946.td.json
Patch FTA scenario as part of release 26.1
```
[ ] Yes
[x] No
```
> 26.1 patch (master)

- src/main/java/uk/gov/hmcts/ccd/security/idam/IdamRepository.java
- src/test/java/uk/gov/hmcts/ccd/security/idam/IdamRepositoryTest.java
https://tools.hmcts.net/jira/browse/CCD-3321
```
[ ] Yes
[ ] No
```
> redesign Idam exception flow

- charts/ccd-data-store-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-3376
AKS is failing in Preview Env - update java  charts
```
[ ] Yes
[x] No
```
> CCD-3376 Update java chart version

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3436
Update dependency-check-suppressions.xml Added temporary suppression for CVE-2022-34305
```
[ ] Yes
[X] No
```
> Update dependency-check-suppressions.xml Added temporary suppression for CVE-2022-34305

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3439
CCD-3439 : Update dependency-check-suppressions.xml - CVE-2022-33915
```
[ ] Yes
[X] No
```
> CCD-3439 : Update dependency-check-suppressions.xml - CVE-2022-33915

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-3515
CVE-2022-22976
```
[ ] Yes
[ ] No
```
> Ccd 3515 CVE 2022 22976

- src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentAmApiClient.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentAmApiClientTest.java
https://tools.hmcts.net/jira/browse/CCD-2555
Fixed
```
[ ] Yes
[x] No
```
> CCD-2555: Fix logging issues

- charts/ccd-data-store-api/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9530
Bump ES chart version for new ingress API version
```
[ ] Yes
[ ] No
```
> Bump es chart version

- charts/ccd-data-store-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9530
Adds nameOverride for service name
```
[ ] Yes
[ ] No
```
> Adds nameOverride for service name

- Jenkinsfile_CNP
- charts/ccd-data-store-api/values.preview.template.yaml
CCD-3609 (https://tools.hmcts.net/jira/browse/CCD-3609)
Changed value of DEFINITION_STORE_URL_BASE in Jenkinsfile_CNP so that it uses https instead of http.
Changed values of DEFINITION_STORE_HOST and USER_PROFILE_HOST in values.preview.template.yaml; replaced ".service.core-compute-preview.internal" with "-java" in both values.
```
[ ] Yes
[x] No
```
> CCD-3609: Fix preview deployment issues

- dependency-check-suppressions.xml
- gradle/suppress.gradle
https://tools.hmcts.net/jira/browse/CCD-3533
Builds on work from #2023 and #2071 
Add code to amend Temporary Suppression section
- new CVEs are now appended to the existing suppress section
- notes section is appended with 'cve name refer Ticket' per new CVE
```
[ ] Yes
[ x] No
```
> CCD-3533 auto amend temp suppression section

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3577
Cleanup CVE Suppressions
```
[ ] Yes
[ x] No
```
> Ccd 3577 cleanup CVE suppressions

- Jenkinsfile_nightly
Reverts hmcts/ccd-data-store-api#2039
> Revert "CCD-3539-CCD-3574: Update Jenkinsfile_nightly (Stop running Nightly builds on weekends, remove FTs)"

- dependency-check-suppressions.xml
> added suppression

- .github/workflows/dependency-check.yml
- dependency-check-suppressions.xml
- gradle/suppress.gradle
https://tools.hmcts.net/jira/browse/CCD-3533
Auto Suppress CVEs 
- validateSection adds Temp Suppress section if missing
- addNewSuppression excludes CVE value if it doesn't start with 'CVE'. Helps if the gradle-java-plugin is not >= 0.12.28
- Added Globals to re-use variables
```
[ ] Yes
[ ] No
```
> Add suppress section

- src/main/java/uk/gov/hmcts/ccd/data/SecurityUtils.java
- src/main/java/uk/gov/hmcts/ccd/data/user/DefaultUserRepository.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleAssignmentsFilteringServiceImpl.java
- src/main/java/uk/gov/hmcts/ccd/security/idam/IdamRepository.java
https://tools.hmcts.net/jira/browse/CCD-3707
https://tools.hmcts.net/jira/browse/CCD-3709
Change logging from info to debug
```
[ ] Yes
[ x] No
```
> CCD-3709 CCD-3707: Amend logging 

- src/main/java/uk/gov/hmcts/ccd/domain/types/NumberValidator.java
https://tools.hmcts.net/jira/browse/CCD-3804
removed
```
[ ] Yes
[x] No
```
> CCD-3804: Remove unwanted info loggers

- gradle.properties
> Increase maximum heap size for the gradle daemon

- src/main/java/uk/gov/hmcts/ccd/domain/enablingcondition/jexl/JexlEnablingConditionParser.java
https://tools.hmcts.net/jira/browse/CCD-3348
removed the stacktrace from the logger
```
[ ] Yes
[x] No
```
> CCD-3348: Remove the stacktrace from the logging message

- dependency-check-suppressions.xml
> Cleanup unwanted CVE suppressions

- src/aat/resources/features/F-037 - Submit Event V2 External/F-037_Test_Data_Base.td.json
- src/aat/resources/features/F-044 - Submit Event V1 External/F-044_Test_Data_Base.td.json
https://tools.hmcts.net/jira/browse/CCD-4010
fixed
```
[ ] Yes
[x] No
```
> CCD-4010: Issue on event_token reported by fortify

- .github/workflows/publish-swagger-specs.yml
- .github/workflows/scheduled-dummy-commit.yml
https://tools.hmcts.net/jira/browse/CCD-3916
Update Github actions in workflow files to resolve deprecation warnings
master branch changed to this branch for dev
```
[ ] Yes
[x ] No
```
> CCD-3916 Update Github actions in workflow

- src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackInvokerWireMockTest.java
https://tools.hmcts.net/jira/browse/CCD-3855
Intermittent test failures
```
[ ] Yes
[x] No
```
> CCD-3855 Intermittent CallbackInvoker test

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4157
Update dependency-check-suppressions.xml
```
[ ] Yes
[X] No
```
> CCD-4157: Update dependency-check-suppressions.xml

- build.gradle
[CCD-4177](https://tools.hmcts.net/jira/browse/CCD-4177)
PR to update test-definition and beta-fw versions.
```
[ ] Yes
[X] No
```
> CCD-4177 Updating test-definition and beta-fw versions

- charts/ccd-data-store-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-4212
bump java chart to 4.0.8
```
[ ] Yes
[X] No
```
> bump java chart to 4.0.9

- src/test/java/uk/gov/hmcts/ccd/data/casedetails/supplementarydata/DefaultSupplementaryDataRepositoryTest.java
https://tools.hmcts.net/jira/browse/CCD-4199
Added more validation in unit tests
```
[ ] Yes
[x] No
```
> CCD-4199 update unit tests to add more validation

- charts/ccd-data-store-api/Chart.yaml
- src/main/java/uk/gov/hmcts/ccd/domain/service/casefileview/FileViewDocumentService.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casefileview/FileViewDocumentServiceTest.java
- src/test/resources/tests/CaseDataExtractorDocumentData.json
https://tools.hmcts.net/jira/browse/CCD-4169
Amend code to work on nested complex types
Fixes StringIndexOutOfBoundsException error message
Add test cases
```
[ ] Yes
[ x] No
```
> CCD-4169 Case File View Error

- src/main/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackService.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackInvokerWireMockTest.java
https://tools.hmcts.net/jira/browse/CCD-3471
Handling CallbackException - Improve Logging   
```
[ ] Yes
[ x] No
```
> Ccd 3471 improve logging

- src/aat/resources/features/F-051 - Get Profile/F-051.feature
- src/aat/resources/features/F-051 - Get Profile/F-051_Test_Data_Base_V1.td.json
- src/aat/resources/features/F-051 - Get Profile/F-051_Test_Data_Base_V2.td.json
- src/aat/resources/features/F-051 - Get Profile/S-104.td.json
- src/aat/resources/features/F-051 - Get Profile/S-105.td.json
- src/aat/resources/features/F-051 - Get Profile/S-106.td.json
- src/aat/resources/features/F-051 - Get Profile/S-107.td.json
- src/aat/resources/features/F-051 - Get Profile/S-108.td.json
- src/aat/resources/features/F-051 - Get Profile/S-109.td.json
- src/aat/resources/features/F-051 - Get Profile/S-110.td.json
[RDM-6432](https://tools.hmcts.net/jira/browse/RDM-6432)
This PR  is to refactor the existing scenarios for the V1 Get user profile endpoint and to add new scenarios for the V2 endpoint.
```
[ ] Yes
[X] No
```
> RDM-6432 - Functional Tests for 'CCD Data Store Api : Get user profile' operation

- charts/ccd-data-store-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-4317
Upgrade base charts
```
[ ] Yes
[X] No
```
> CCD-4317 Upgrade base charts

- build.gradle
- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
https://tools.hmcts.net/jira/browse/CCD-4207
Update hazelcast to fix CVE-2022-36437
```
[ ] Yes
[ ] No
```
> CCD-4207 Update hazelcast to fix CVE-2022-36437

- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/PseudoRoleToAccessProfileGenerator.java
- src/test/java/uk/gov/hmcts/ccd/MockUtils.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/PseudoRoleToAccessProfileGeneratorTest.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerEventsIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UICaseControllerCaseRolesIT.java
- src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UIStartEventControllerCaseRolesIT.java
- src/test/resources/mappings/bookcase-no-event-access-to-caserole-definition.json
- src/test/resources/mappings/case-roles-definition.json
- src/test/resources/sql/insert_cases_event_access_case_roles.sql
https://tools.hmcts.net/jira/browse/CCD-4390
Update Caseroles regular expression
```
[ ] Yes
[x] No
```
> CCD-4390 initial commit

- src/main/java/uk/gov/hmcts/ccd/domain/service/common/SimpleCaseTypeMetadataExtractor.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AbstractBaseCaseFieldMetadataExtractorTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/SimpleCaseTypeMetadataExtractorTest.java
Include custom Document types
https://tools.hmcts.net/jira/browse/CCD-4457
```
[ ] Yes
[x ] No
```
> CCD-4457 Include custom Document types

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-4599
Bump sonarkube version to 2.7
```
[ ] Yes
[X] No
```
> CCD-4599 : Update build.gradle

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4479
https://tools.hmcts.net/jira/browse/CCD-4509
Fix for CVE-2023-20861
Fix for CVE-2023-20860
upgrade  Spring Framework version to 5.3.26
```
[ ] Yes
[x] No
```
> CCD-4479, CCD-4509- Fix for CVE-2023-20861,CVE-2023-20860 

- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceImpl.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceTest.java
> Switch common log message back to debug

- charts/ccd-data-store-api/values.yaml
- src/main/java/uk/gov/hmcts/ccd/data/user/DefaultUserRepository.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceImpl.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceTest.java
Further changes to reduce unnecessary logging - see PR comments for rationale behind each change.
```
[ ] Yes
[x] No
```
> Further changes to reduce unnecessary logging

- .github/renovate.json
- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.yaml
- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/ccd/data/user/DefaultUserRepository.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceImpl.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceTest.java
Merge master into develop
```
[ ] Yes
[ X] No
```
> Merge master into develop

- src/aat/resources/features/F-027 - Get Case Data V1 Internal/S-590.td.json
- src/aat/resources/features/F-104 - Internal Search API/Base_Case_Fields_Expected.td.json
- src/aat/resources/features/F-109 - caseworker-caa Authorisation/Base_Case_Fields__internal_Expected.td.json
- src/aat/resources/features/F-120 supplementary_data in ES Search API/S-120.3.td.json
- src/aat/resources/features/F-120 supplementary_data in ES Search API/S-120.4.td.json
- src/contractTest/resources/application.properties
- src/main/resources/application.properties
- src/test/java/uk/gov/hmcts/ccd/ElasticsearchIT.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/CaseSearchResultViewGeneratorTest.java
#2284 but disabled by default.
```
[ ] Yes
[x] No
```
> CCD-4795 - Disable feature flag by default

- src/contractTest/resources/application.properties
- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
- src/main/resources/application.properties
- src/test/resources/test.properties
> CCD-4787: Increase ttl for user role cache to two hours

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4738
CCD-4738 : Fix CVE-2023-33264 (Bumped version of Hazelcast)
```
[ ] Yes
[X] No
```
> CCD-4738 : Fix CVE-2023-33264 (Bumped version of Hazelcast)

- src/aat/resources/features/F-1020 - Get Case Events On Behalf Of UserId/F-1020.feature
- src/aat/resources/features/F-1020 - Get Case Events On Behalf Of UserId/F1020_Case_Data_Create.td.json
- src/aat/resources/features/F-1020 - Get Case Events On Behalf Of UserId/F1020_Case_Data_Create_C1.td.json
- src/aat/resources/features/F-1020 - Get Case Events On Behalf Of UserId/F1020_Case_Data_Create_C1_Token_Creation.td.json
- src/aat/resources/features/F-1020 - Get Case Events On Behalf Of UserId/F1020_Case_Data_Create_Token_Creation.td.json
- src/aat/resources/features/F-1020 - Get Case Events On Behalf Of UserId/F1020_Get_CaseEvent_With_On_Behalf_Of_User.td.json
- src/aat/resources/features/F-1020 - Get Case Events On Behalf Of UserId/F1020_Prerequisite_Citizen_Token_For_Update_Case.td.json
- src/aat/resources/features/F-1020 - Get Case Events On Behalf Of UserId/F1020_Update_Case_With_On_Behalf_Of_User.td.json
- src/aat/resources/features/F-1020 - Get Case Events On Behalf Of UserId/S-1020.td.json
- src/aat/resources/features/F-1021 - On Behalf Of User Id after Case created Get events by case ID/F-1021.feature
- src/aat/resources/features/F-1021 - On Behalf Of User Id after Case created Get events by case ID/F-1021_Standard_Full_Case_Creation_Data.json
- src/aat/resources/features/F-1021 - On Behalf Of User Id after Case created Get events by case ID/F-1021_Test_Data_Base.td.json
- src/aat/resources/features/F-1021 - On Behalf Of User Id after Case created Get events by case ID/S-1021.1.td.json
https://tools.hmcts.net/jira/browse/SDT-133
https://tools.hmcts.net/jira/browse/SDT-134
```
[ ] Yes
[ ] No
```
> SDT-133: Befta test cases Support for onBehalfOfUserId to Create and Update events on CCD Data Store

- infrastructure/apps-insight.tf
NA
removed .tf appinsights-connection-string as resource already exists
```
[ ] Yes
[X] No
```
> Update apps-insight.tf removed connection-string

- src/aat/resources/features/F-1005 - GlobalSearch - Search cases/F-1005.feature
> Update Feature 1005

- infrastructure/prod.tfvars
> Update prod.tfvars to match prod

- src/main/java/uk/gov/hmcts/ccd/appinsights/AppInsights.java
- src/main/java/uk/gov/hmcts/ccd/appinsights/AppInsightsConfiguration.java
> initialise telemetry

- src/main/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepository.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseTypesOperation.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetUserProfileOperation.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseTypeDefinitionsOperationTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetUserProfileOperationTest.java
> fix jurisdiction missing state issue

- Jenkinsfile_CNP
> CCD-4837 -- Disable Demo branch sync

- src/main/java/uk/gov/hmcts/ccd/data/definition/CachedUIDefinitionGateway.java
- src/test/java/uk/gov/hmcts/ccd/integrations/DefinitionsCachingIT.java
https://tools.hmcts.net/jira/browse/CCD-4981
```
[ ] Yes
[ ] No
```
> temporary disable cache entries

- src/main/java/uk/gov/hmcts/ccd/data/definition/CachedUIDefinitionGateway.java
- src/test/java/uk/gov/hmcts/ccd/integrations/DefinitionsCachingIT.java
Reverts hmcts/ccd-data-store-api#2317
> Revert "temporary disable cache entries"

- src/main/java/uk/gov/hmcts/ccd/data/definition/UIDefinitionRepository.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/WizardPage.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/WizardPageComplexFieldOverride.java
- src/main/java/uk/gov/hmcts/ccd/domain/model/definition/WizardPageField.java
- src/test/java/uk/gov/hmcts/ccd/domain/model/definition/WizardPageTest.java
- src/test/java/uk/gov/hmcts/ccd/integrations/DefinitionsCachingIT.java
- src/test/resources/mappings/base-types.json
- src/test/resources/tests/FT-ComplexCollectionComplex-event-createSchool-payload.json
- src/test/resources/tests/FT-Conditionals-event-createCase-payload.json
- src/test/resources/tests/FT-MasterCaseType-event-createCase-payload.json
https://tools.hmcts.net/jira/browse/CCD-4991
```
[ ] Yes
[ ] No
```
> implement wizardPage defensive copy

- Jenkinsfile_CNP
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/ithc.tfvars
- infrastructure/main.tf
- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
- infrastructure/state.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-4837
Terraform file for upgrading data store to v15 flexible servers
```
[ ] Yes
[x] No
```
> Upgrade data store v15 for ccd-data-store-api

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4771
bumped jackson version, removed suppression
```
[ ] Yes
[X] No
```
> CCD-4771 : Fix CVE-2023-35116

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4970
updated guava and removed suppression
```
[ ] Yes
[X] No
```
> CCD-4970 : Fix CVE-2020-8908

- dependency-check-suppressions.xml
- infrastructure/aat.tfvars
- infrastructure/ithc.tfvars
- infrastructure/main.tf
- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-4837
Updating the subnet suffix 
```
[ ] Yes
[x] No
```
> Updating subnet suffix

- infrastructure/perftest.tfvars
> Update performance test configurations

- infrastructure/aat.tfvars
- infrastructure/prod.tfvars
> Updating prod and aat to memory optimised

- src/main/java/uk/gov/hmcts/ccd/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/v2/external/controller/TestingSupportController.java
- src/main/resources/application.properties
- src/test/resources/test.properties
> Add testing-support/cleanup-case-type to security whitelist

- src/main/java/uk/gov/hmcts/ccd/v2/external/controller/TestingSupportController.java
Fixes error:
```json
{"exception":"java.lang.IllegalStateException","status":500,"error":"Unexpected Error","message":"Transaction already active","path":"/testing-support/cleanup-case-type/123/","details":null,"callbackErrors":null,"callbackWarnings":null,"timestamp":"2023-11-23T14:24:10.730438744"}
```
```
[ ] Yes
[x] No
```
> remove duplicate session creation

- .github/workflows/publish-swagger-specs.yml
[DTSPO-16053](https://tools.hmcts.net/jira/browse/DTSPO-16053)
Use swagger api token instead of github token when checking out `cnp-api-docs`
```
[ ] Yes
[x] No
```
> Use swagger api token instead of github token

- src/aat/resources/features/F-1022 - CaseAccessGroups Complex Type/F-1022.feature
- src/aat/resources/features/F-1022 - CaseAccessGroups Complex Type/F-1022_CaseworkerUpdateCaseEvent.td.json
- src/aat/resources/features/F-1022 - CaseAccessGroups Complex Type/F-1022_CreateCase.td.json
- src/aat/resources/features/F-1022 - CaseAccessGroups Complex Type/F-1022_GetCaseworkerUpdateToken.td.json
- src/aat/resources/features/F-1022 - CaseAccessGroups Complex Type/F-1022_Get_Event_Token_Base.td.json
- src/aat/resources/features/F-1022 - CaseAccessGroups Complex Type/F-1022_SearchCaseBase.td.json
- src/aat/resources/features/F-1022 - CaseAccessGroups Complex Type/F-1022_Test_Data_Base.td.json
- src/aat/resources/features/F-1022 - CaseAccessGroups Complex Type/S-1022.1.td.json
- src/aat/resources/features/F-1022 - CaseAccessGroups Complex Type/S-1022.2.td.json
- src/aat/resources/features/F-1022 - CaseAccessGroups Complex Type/S-1022.3.td.json
> GA-2-4 - Case Access Group Acceptance Criteria Test case changes

- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-16954
Added var for auto_grow_enabled in flex server and set it to true in prod. This matches single server setup
```
[ ] Yes
[ ] No
```
> Setting storage auto growth to true in aat and prod

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5136
Changed versions to resolve CVE
```
[ ] Yes
[x] No
```
> Bumped versions but still pulling in old version

- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CCD-5180
> CCD-5180 flexible server database fix perms

- src/contractTest/resources/application.properties
- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentTimestampService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/hmcts/ccd/domain/service/createevent/CreateCaseEventServiceTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentTimestampServiceTest.java
https://tools.hmcts.net/jira/browse/CSFD-97
Feature toggle the add upload timestamp logic
```
[ ] Yes
[x] No
```
> CSFD-97 [Case Create/Update] Populate Document's "upload_timestamp" Value - Feature Toggle

- src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceImpl.java
https://tools.hmcts.net/jira/browse/CIV-13093
need ccd data store log error fields for further investigation
```
[ ] Yes
[x] No
```
> CIV-13093 log error fields

- infrastructure/prod.tfvars
Changing the memory sku within prod in order to align with current memory sku configuration on live servers 
```
[ ] Yes
[ ] No
```
> Updating memory sku with live servers

- Jenkinsfile_CNP
Temporarily disable to unblock pipelines after failures from no changes (DTSPO-17343)
```
[ ] Yes
[ ] No
```
> Disable PACT

- src/main/java/uk/gov/hmcts/ccd/domain/model/common/CaseFieldPathUtils.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/processor/GlobalSearchProcessorService.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/processor/GlobalSearchProcessorServiceTest.java
https://tools.hmcts.net/jira/browse/CCD-5337
```
[ ] Yes
[ ] No
```
> refine SearchCriteria field by eliminating null values.

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5160
CCD-5160: bumped jackson.version to 2.16.0
```
[ ] Yes
[X] No
```
> CCD-5160: bumped jackson.version to 2.16.0

- infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CCD-5310
Update azuread to 2.48 as part of renovate change
> Update azuread to 2.48 as part of renovate change

- src/aat/resources/features/F-1006 - GlobalSearch - AC tests/F-1006_SearchCaseBaseRestricted.td.json
- src/aat/resources/features/F-1006 - GlobalSearch - AC tests/S-1006.2.td.json
https://tools.hmcts.net/jira/browse/CCD-5438
Fix for failing pipeline build (FT)
```
[ ] Yes
[X] No
```
> Fix for failing FT in pipeline build

- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.yaml
> CCD-5232 Update values.yaml to flexible server

- infrastructure/prod.tfvars
Reverts hmcts/ccd-data-store-api#2420
> Revert "CCD-5232 Update prod.tfvars scale down v11 D/B"

- charts/ccd-data-store-api/Chart.yaml
- charts/ccd-data-store-api/values.yaml
> merge ithc into master

- src/aat/resources/features/F-1020 - Get Case Events On Behalf Of UserId/F1020_Get_CaseEvent_With_On_Behalf_Of_User.td.json
- src/aat/resources/features/F-1020 - Get Case Events On Behalf Of UserId/F1020_Update_Case_With_On_Behalf_Of_User.td.json
- src/aat/resources/features/F-1021 - On Behalf Of User Id after Case created Get events by case ID/F-1021_Standard_Full_Case_Creation_Data.td.json
- src/aat/resources/features/common/users/GroupAccessCaseworkerAutotest.td.json
> fix fortify issues

- src/test/java/uk/gov/hmcts/ccd/AbstractBaseIntegrationTest.java
- src/test/java/uk/gov/hmcts/ccd/ElasticsearchIT.java
- src/test/java/uk/gov/hmcts/ccd/data/caselinking/CaseLinkRepositoryTest.java
- src/test/java/uk/gov/hmcts/ccd/integrations/CaseRoleDefinitionCachingIT.java
- src/test/java/uk/gov/hmcts/ccd/integrations/DefinitionsCachingIT.java
- src/test/java/uk/gov/hmcts/ccd/integrations/IdamRepositoryCachingIT.java
> Ccd 4262 4769 unit test failure fix

- src/main/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepository.java
- src/test/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepositoryTest.java
https://tools.hmcts.net/jira/browse/CCD-5587
```
[ ] Yes
[ ] No
```
> change CaseConcurrencyException message and add unit test

- build.gradle
> fixing missing citizen data in excel for FT tests

- build.gradle
> CCD-5311 Fix CVE-2023-20873

- src/main/java/uk/gov/hmcts/ccd/v2/external/controller/TestingSupportController.java
- src/test/java/uk/gov/hmcts/ccd/v2/external/controller/TestingSupportControllerTest.java
- [ x] commit messages are meaningful and follow good commit message guidelines
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CCD-5625
Deleting records from case_link for a given case type.
```
[ ] Yes
[x ] No
```
>  CCD-5625: Case types on XUI AAT are not getting cleared after PR merge

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5158
Fix CVE-2023-46589
```
[ ] Yes
[x] No
```
> CCD-5158 - Fix CVE-2023-46589

- dependency-check-suppressions.xml
> tidy up suppressions

- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/CaseDefinitionRepository.java
- src/main/java/uk/gov/hmcts/ccd/data/definition/DefaultCaseDefinitionRepository.java
- src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControl.java
- src/test/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepositoryTest.java
- src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControlTest.java
https://tools.hmcts.net/jira/browse/CCD-4833
```
[ ] Yes
[ ] No
```
> implement scopedCachedCaseType and use in /searchCases;/globalSearch

- .github/workflows/dependency-check.yml
- .github/workflows/publish-swagger-specs.yml
- .travis.yml
- Dockerfile
- README.md
- acb.tpl.yaml
- build.gradle
- src/test/resources/test.properties
https://tools.hmcts.net/jira/browse/CME-40
Update to Java 21
```
[ ] Yes
[x] No
```
> CME-40 update to Java 21

- build.gradle
- lib/applicationinsights.json
- src/main/java/uk/gov/hmcts/ccd/config/CacheConfiguration.java
> Ccd 5483 enable caffeine cache stats

- build.gradle
> CME-109 to use ccd-test-definition version 7.24.0

- src/main/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/DefaultRoleAssignmentRepository.java
https://tools.hmcts.net/jira/browse/CCD-5965
```
[ ] Yes
[ ] No
```
> replace get(0) with getFirst to handle null from RoleAssignment

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-6049
bumped test-definitions to latest
```
[ ] Yes
[X] No
```
> CCD-6049 : bumped test-definitions to latest

- charts/ccd-data-store-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```
> CCD-6193 update base chart versions

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-6254
Fortify fix
```
[ ] Yes
[ ] No
```
> CCD-6254-data-store

- src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/CasesControllerProviderTest.java
[
](https://tools.hmcts.net/jira/browse/CCD-6259)
```
[ ] Yes
[ ] No
```
> ccd-data-store-Fortify-fixccd-6259

- src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/CasesControllerProviderTest.java
- src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/caseassigned/CaseAssignedUserRolesProviderTest.java
- src/contractTest/java/uk/gov/hmcts/reform/ccd/pactprovider/cases/CasesProviderTest.java
- src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilder.java
> CME-289: Set consumerVersionSelectors to master

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-480
```
[ ] Yes
[ x] No
```
> CME-480: Add database monitoring

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CFTS-6913
Suppressed CVE
```
[ ] Yes
[X] No
```
> CFTS-6913 : Suppress CVE

- Jenkinsfile_CNP
- build.gradle
> CME-289: Suppress pact tests to unblock ccd-data store

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6458
Suppression
```
[ ] Yes
[X] No
```
> CCD-6458 :: Update dependency-check-suppressions.xml

- src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
- src/main/java/uk/gov/hmcts/ccd/domain/types/sanitiser/DocumentSanitiser.java
- src/test/java/uk/gov/hmcts/ccd/domain/types/sanitiser/DocumentSanitiserTest.java
- src/test/resources/mappings/dm-documents.json
Reverts hmcts/ccd-data-store-api#1973
> Revert "switched document retrieve call from dm-store to cdam"

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6601
Suppress CVE's reported
```
[ ] Yes
[X] No
```
> CCD-6601 :: Update dependency-check-suppressions.xml

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6640
CCD-6640 :: Multiple CVE Suppressions
```
[ ] Yes
[X] No
```
> CCD-6640 :: Multiple CVE Suppressions

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6636
CCD 6636 :: Fix CVE
```
[ ] Yes
[X] No
```
> CCD 6636 :: Fix CVE

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/CCD-6630
CCD-6630 :: trigger upstream job guild via downstream job
```
[ ] Yes
[X] No
```
> CCD-6630 :: trigger upstream job guild via downstream job

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6797
CVE Suppression
```
[ ] Yes
[X] No
```
> CCD-6797 :: Add Suppression
