hmcts/ccd-data-store-api

src/main/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackService.java
src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackServiceTest.java

https://tools.hmcts.net/jira/browse/RDM-1982
Timeout for callbacks were not applied. Added a fix for this and added a timeout test
```
[ ] Yes
[X] No
```

RDM-1982 Timeout configuration applied to RestTemplate object

---

src/main/java/uk/gov/hmcts/ccd/data/casedetails/CachedCaseDetailsRepository.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseDetailsRepository.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepository.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilder.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilderFactory.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/CountCaseDetailsQueryBuilder.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/SelectCaseDetailsQueryBuilder.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/UserAuthorisationSecurity.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/SearchQueryFactoryOperation.java
src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessService.java
src/main/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisation.java
src/main/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationConfiguration.java
src/main/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationFactory.java
src/test/java/uk/gov/hmcts/ccd/data/casedetails/CachedCaseDetailsRepositoryTest.java
src/test/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepositoryTest.java
src/test/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilderFactoryTest.java
src/test/java/uk/gov/hmcts/ccd/data/casedetails/query/UserAuthorisationSecurityTest.java
src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/SQLBuilderForSearchTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessServiceTest.java
src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
src/test/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationConfigurationTest.java
src/test/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationFactoryTest.java
src/test/resources/sql/insert_case_users.sql
src/test/resources/sql/insert_cases.sql

https://tools.hmcts.net/jira/browse/RDM-1448
Enforce user access constraints as part of the SQL queries. This allows pagination on search to stay accurate when cases are filtered out by this constraint.
```
[ ] Yes
[x] No
```

RDM-1448: Enforce user access at DB level

---

src/main/java/uk/gov/hmcts/ccd/domain/types/sanitiser/DocumentSanitiser.java
src/test/java/uk/gov/hmcts/ccd/domain/types/sanitiser/DocumentSanitiserTest.java

https://tools.hmcts.net/jira/browse/RDM-1985
Attempt to sanitise null document throws NPE. This add checks to only sanitise documents that are not null nodes.
```
[ ] Yes
[x] No
```

Do not sanitise null document

---

infrastructure/main.tf
infrastructure/outputs.tf
infrastructure/preview.tfvars

N/A
At the moment, no vault is setup for preview environment; as such preview build fails.
This makes preview deployments use the existing AAT vault.
```
[ ] Yes
[x] No
```

Setup vault for preview

---

src/main/resources/db/changelog/db.changelog-RDM-2230.xml
src/main/resources/db/changelog/db.changelog-master.xml

https://tools.hmcts.net/jira/browse/RDM-2230
Definition store dictates that event IDs have a max length of 70 chars. However, data store only support max length of 40 chars. This is updating the column to be `varchar(70)`.
```
[ ] Yes
[x] No
```

RDM-2230: Support event ID max length 70 chars

---

src/aat/java/uk/gov/hmcts/ccd/datastore/tests/helper/idam/IdamApi.java

This PR is for fixing the functional tests of sIdam.
Same solution applied in ccd-definition-store-api
The idam requests are altered to send the content in body instead of the query string.
```
[ ] Yes
[X] No
```

fix for functional tests & sIdam Integration

---

src/main/resources/application.properties

Correct URL to access the Print Service via the API Gateway (to ensure correct setting of authentication header), instead of directly.
None.
Sets the default Print Service URL to access the service via the API Gateway, not directly.
```
[ ] Yes
[x] No
```

Correct default Print Service URL

---

build.gradle

https://tools.hmcts.net/jira/browse/RDM-2485
Remove dependency on JUnit 4 (covered by JUnit 5 Vintage)
Remove JUnitPlatform plugin (native since Gradle 4.6)
Unify JUnit configs
Increase coverage limits to reflect combined coverage (JUnit 4 + 5)
```
[ ] Yes
[x] No
```

RDM-2485: Fix JUnit 4/5 conflicts

---

src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseDataService.java
src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationService.java
src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseDataServiceTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationServiceTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
src/test/resources/mappings/bookcase-definition.json

https://tools.hmcts.net/jira/browse/RDM-2438
Fixes RDM-2438
Classifications for simple collections were store as `classification` but read as `value`. As such, classifications were not found and by default items were filtered out.
Add fallback to read classification from `classification` node
This is a quick fix to restore the use of simple collections. Additional work around classifications on collections will be provided as part of RDM-882.
```
[ ] Yes
[x] No
```

RDM-2438: Fix classifications on simple collections

---

src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationService.java
src/test/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationServiceTest.java

https://tools.hmcts.net/jira/browse/RDM-882
Couple of tests were assuming that classification structure for simple collection was:
```json
{
"Addresses": [
{
"id": "xxx-xxx-xxx",
"value": {
"Address1": "PRIVATE"
}
}
]
}
```
This seems to be a confusion between structure for simple and complex collection. Actual structure for simple collection is:
```json
{
"Addresses": [
{
"id": "xxx-xxx-xxx",
"classification": "PRIVATE"
}
]
}
```
As supported by function `CaseDataService#deduceClassificationForCollectionType()` which does:
```java
final ObjectNode simpleCollectionItemNode = (ObjectNode) field;
// Add `classification` property
deduceClassificationForSimpleType(simpleCollectionItemNode, existingDataClassificationNode, CLASSIFICATION, caseField);
// Remove `value` property …
```

RDM-882: Cleanup collection classification structure

---

src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/MetaData.java
src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/AbstractCaseView.java
src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewField.java
src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewFieldBuilder.java
src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetails.java
src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseField.java
src/main/java/uk/gov/hmcts/ccd/domain/model/definition/SearchResultField.java
src/main/java/uk/gov/hmcts/ccd/domain/model/search/Field.java
src/main/java/uk/gov/hmcts/ccd/domain/model/search/SearchResultView.java
src/main/java/uk/gov/hmcts/ccd/domain/model/search/SearchResultViewColumn.java
src/main/java/uk/gov/hmcts/ccd/domain/model/search/SearchResultViewItem.java
src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AbstractDefaultGetCaseViewOperation.java
src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultFindSearchInputOperation.java
src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultFindWorkbasketInputOperation.java
src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetCaseViewOperation.java
src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetEventTriggerOperation.java
src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/MergeDataToSearchResultOperation.java
src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/SearchQueryOperation.java
src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlService.java
src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpoint.java
src/main/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpoint.java
src/test/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetailsTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultFindSearchInputOperationTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultFindWorkbasketInputOperationTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetCaseViewOperationTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/MergeDataToSearchResultOperationTest.java
src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java

https://tools.hmcts.net/jira/projects/RDM/issues/RDM-626
Code changes to support metadata fields in search results. Also did a little refactoring from array to list for the search results and made case fields data type more generic rather than a map of String and JsonNode, it is now a map of String and Object. Please review
```
[ ] Yes
[ x] No
```

NEW - RDM-626 - Display metadata in search results

---

dependency-check-suppressions.xml

We don't use Spring Framework 5.0.5.RELEASE + Spring Security (any
version)
https://tools.hmcts.net/jira/browse/RDM-2464
```
[ ] Yes
[X] No
```

[SKIP-PREVIEW] Suppress CVE-2018-1258 impacted products are not used

---

dependency-check-suppressions.xml

This CVE relates to Ethereum but is brought in by Codacy so does not
impact production.
https://tools.hmcts.net/jira/browse/RDM-2831
```
[ ] Yes
[x] No
```

Supress CVE-2018-13661 in codacy dependency

---

build.gradle
dependency-check-suppressions.xml

- We don't manage the PG installation
- The version on Azure that we use is not impacted
https://tools.hmcts.net/jira/browse/RDM-3175
```
[ ] Yes
[x] No
```

CVE: suppress CVE-2016-7048

---

infrastructure/main.tf
src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseDetailsEntity.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepository.java
src/main/java/uk/gov/hmcts/ccd/health/ElasticSearchHealthIndicator.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/ccd/health/ElasticSearchHealthIndicatorTest.java

https://tools.hmcts.net/jira/browse/RDM-3008
An example of the generated health check is provided in the ticket
```
[ ] Yes
[x ] No
```

[PREVIEW] implemented ElasticSearch health check. Added publishing of ES password

---

src/main/java/uk/gov/hmcts/ccd/health/ElasticSearchHealthIndicator.java
src/test/java/uk/gov/hmcts/ccd/health/ElasticSearchHealthIndicatorTest.java

On Sprod where we have lot's of db data, the ES HealthCheck is performing too slow and cause the /health endpoint to hit the timeout. Because of this the pipeline cannot deploy data store on Sprod.
This change is for temporarily make the ES HealthCheck faster by removing the call to the db. We will reintroduced this later on with a more performant version
```
[ ] Yes
[ x] No
```

made ES Health Check lighter

---

src/main/resources/application.properties

https://tools.hmcts.net/jira/browse/RDM-3271
- Set minimum idle to 8, previous minimum and maximum
- Set maximum connections to 16, previously 8
- Set idle timeout to 5 min so that extra connections are quickly freed, previously not used
- Set connection timeout to 40s, previously 30s
```
[ ] Yes
[x] No
```

RDM-3271: Tune Hikari connection pool

---

src/aat/java/uk/gov/hmcts/ccd/datastore/tests/functional/elasticsearch/ElasticsearchBaseTest.java
src/aat/java/uk/gov/hmcts/ccd/datastore/tests/functional/elasticsearch/ElasticsearchCaseSearchSecurityTest.java
src/aat/java/uk/gov/hmcts/ccd/datastore/tests/functional/elasticsearch/ElasticsearchCaseSearchTest.java
src/aat/java/uk/gov/hmcts/ccd/datastore/tests/functional/elasticsearch/ElasticsearchHelper.java

https://tools.hmcts.net/jira/browse/RDM-3125
Fix for running ES functional test only when ELASTIC_SEARCH_ENABLED is set to true
```
[ ] Yes
[X] No
```

RDM-3125 - fix for enabling test when elasticsearch enabled

---

src/main/java/uk/gov/hmcts/ccd/domain/types/CaseDataValidator.java
src/main/java/uk/gov/hmcts/ccd/domain/types/FixedRadioListValidator.java
src/test/java/uk/gov/hmcts/ccd/domain/types/FixedRadioListValidatorTest.java

https://tools.hmcts.net/jira/browse/RDM-1893
As a caseworker
I want to see multiple options in radio button rather than Dropdown
So that I can see all the available options at one go and select one accordingly.
```
[ ] Yes
[X] No
```

Rdm 1893 - Add FixedRadioList validator

---

infrastructure/aat.tfvars
infrastructure/main.tf
infrastructure/variables.tf
src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
src/main/resources/application.properties

Fix AAT performance issues:
Removed limit on cache size. 
Made definition cache parameters configurable. 
Increased ttl of a cache entry to 3 days
ADDITIONAL INFO:
https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#map
```
[ ] Yes
[ x] No
```

Attempt to fix AAT performance issues

---

dependency-check-suppressions.xml

Suppresses: CVE-2018-1000873, CVE-2018-14718, CVE-2018-14719,
CVE-2018-14720, CVE-2018-14721, CVE-2018-19360, CVE-2018-19361,
CVE-2018-19362
https://tools.hmcts.net/jira/browse/RDM-3796
```
[ ] Yes
[ ] No
```

Temporarily suppress jackson-databind CVEs

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/RDM-3796
* Upgrades spring boot to 1.15.19 - things bring in jackson-databind
2.8.11.3 which address most of the CVEs
* Suppress false positive CVEs
* Suppress CVE-2018-1000873 which won't get fixed on the 2.8.x release
brnach
```
[ ] Yes
[ ] No
```

Upgrade springboot to 1.15.19 to address jackson-databind CVEs

---

infrastructure/main.tf

Set this to the max.  Though we have tonnes of logs which blow us part
2GB for the app.
```
[ ] Yes
[ ] No
```

Bump webapp cache to 2000

---

src/aat/java/uk/gov/hmcts/ccd/datastore/tests/fixture/AATCaseType.java
src/test/java/uk/gov/hmcts/ccd/data/definition/CaseDefinitionRepositoryWireMockNotRunningTest.java

This test failure is safe to ignore for the moment until we fix it. I'm issuing this PR to temporarily disable the test so we unblock the pipeline. The test is failing because we introduced caching on the tested method the other day. But the cache provide Hazelcast for some reason sometimes is shut down by the test framework and so is not available when the test runs. Causing the exception.
```
[ ] Yes
[ x] No
```

temporarily disabling failing test to unblock the pipeline

---

src/main/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackService.java
src/main/java/uk/gov/hmcts/ccd/domain/service/stdapi/CallbackInvoker.java
src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackServiceTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/stdapi/CallbackInvokerTest.java

Added retry with default backoff of 1, 3 secs if the initial request fails. 
After the chat we had with Stuart and Mario, we decided to use the Spring Retry until the requirements here are clarified.
https://tools.hmcts.net/jira/browse/RDM-4316
```
[ ] Yes
[X] No
```

RDM-4316 fix broken callback retry mechanism

---

src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewFieldBuilder.java
src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseField.java
src/main/java/uk/gov/hmcts/ccd/domain/model/definition/FieldType.java
src/test/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewFieldBuilderTest.java
src/test/java/uk/gov/hmcts/ccd/domain/model/definition/CaseFieldTest.java
src/test/java/uk/gov/hmcts/ccd/domain/model/definition/FieldTypeTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java

https://tools.hmcts.net/jira/browse/RDM-4372
A small change to get children when the case when a complex type contains collections.
```
[ ] Yes
[ X] No
```

RDM 4372 Fix for error when complex type contains collections

---

infrastructure/main.tf
infrastructure/variables.tf

N/A
Removed an invalid value for `external_host_name` and setting it via a TF variable.
This is to enable the following PR to be merged: https://github.com/hmcts/cnp-module-webapp/pull/145
```
[ ] Yes
[x] No
```

Added a TF variable for setting custom webapp domain

---

charts/ccd-data-store-api/values.yaml

This reverts commit 0ad5f6f9d85e643c54f617ca8f49c52cd4c65db5.
chart-java 2.0.5 provides a proper fix
```
[ ] Yes
[ ] No
```

Revert "Lock postgresql image in Helm"

---

lib/AI-Agent.xml

https://tools.hmcts.net/jira/browse/RDM-5147
Set SQL query duration (MaxStatementQueryLimitInMS) above which query plan is reported. Default is 10000 ms. This should fix the error occurring on some transactions `ERROR: current transaction is aborted, commands ignored until end of transaction block ERROR:`
```
[ ] Yes
[ x] No
```

RDM-5147 - setting MaxStatementQueryLimitInMS to default value.

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/RDM-3551
Fixed CVE-2019-10072 by upgrading tomcat libraries. 
Other one CVE-2019-12814 jackson-databind has to suppress for now.  
```
[ ] Yes
[ x] No
```

Jackson CVE failures 

---

src/main/java/uk/gov/hmcts/ccd/domain/service/common/CompoundAccessControlService.java
src/test/java/uk/gov/hmcts/ccd/domain/service/common/CompoundAccessControlServiceTest.java

Fix for null pointer exception when a child field with null values is updated to a new value.
```
[ ] Yes
[X] No
```

RDM-4068 npe fix for complex field updates on case fields with null initial value

---

Jenkinsfile_CNP
charts/ccd-data-store-api/Chart.yaml
charts/ccd-data-store-api/values.aat.template.yaml
infrastructure/main.tf
infrastructure/outputs.tf
src/main/resources/bootstrap.yaml

-
https://github.com/hmcts/cnp-jenkins-library/pull/533 changed to using the component for looking up the vault prefix, it was expected that all teams were doing this, inside of your own vault there is no need to prefix the secret with the product.
```
[ ] Yes
[ ] No
```

Fix deprecation issues and use component for vault

---

src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java

From Praveen: 
```
ccd data store talks to 54.225.98.182 
this has made secops not approve Data Store for prod
ip is hazelcast doing home calling
```
Ref:
https://docs.hazelcast.org/docs/3.9.2/manual/html-single/index.html#Disabling-Phone-Homes
```
[ ] Yes
[x ] No
```

Disabling Hazelcast Phone Homes for security purposes

---

charts/ccd-data-store-api/Chart.yaml
charts/ccd-data-store-api/requirements.yaml

bulk-scanning is currently blocked because of a clash in the tpl in an old version of chart-java, this was fixed in ~2.10
```
[ ] Yes
[ x] No
```

RDM-6596-bumped java chart version

---

build.gradle

Reverts hmcts/ccd-data-store-api#772 - quick fix / hack didn't work so better to revert

Revert "Temp sonar exclusions"

---

src/aat/resources/features/F-026/S-078.td.json
src/aat/resources/features/F-051/S-110.td.json

The header "Transfer-Encoding" is not always returned, causing functional tests to fail on some PRs.
```
[ ] Yes
[x ] No
```

Remove unexpected header from test

---

build.gradle

https://tools.hmcts.net/jira/browse/RDM-7733
Update jackson-databind for CVE-2020-8840
```
[ ] Yes
[x] No
```

RDM-7733 - Update jackson-databind

---

build.gradle

[RDM-7833](https://tools.hmcts.net/jira/browse/RDM-7833)
Bump `org.apache.tomcat.embed` version from `9.0.30` to `9.0.31` for *CVE-2020-1938*.
```
[ ] Yes
[x] No
```

RDM-7833 Fix tomcat security issue CVE-2020-1938

---

src/aat/resources/features/F-051/S-109.td.json

zipped content length can vary depending on ordering of chars in a text 
```
[ ] Yes
[X] No
```

zipped content length can vary depending on ordering of chars in a text

---

src/aat/resources/features/F-051/S-109.td.json
src/main/java/uk/gov/hmcts/ccd/domain/service/processor/DateTimeFormatParser.java
src/main/java/uk/gov/hmcts/ccd/domain/service/processor/DisplayContextParameter.java
src/test/java/uk/gov/hmcts/ccd/domain/service/processor/DateTimeFormatParserTest.java

https://tools.hmcts.net/jira/browse/RDM-8113
RDM-8113 handle display without seconds or milliseconds
RDM-8057 split DCP correctly when there is multiple params
```
[ ] Yes
[X] No
```

RDM-8113 handle display without seconds or milliseconds

---

src/main/java/uk/gov/hmcts/ccd/domain/model/search/CaseSearchResult.java

temporarily excluding new property 'case_types_results' from serialisation to fix broken client 'core-case-data-store-client' library who is not expecting that property:
```
Request processing failed; nested exception is feign.FeignException: Unrecognized field "case_types_results" (class uk.gov.hmcts.reform.ccd.client.model.SearchResult), not marked as ignorable (2 known properties: "cases", "total"])
at [Source: (BufferedReader); line: 1, column: 42617] (through reference chain: uk.gov.hmcts.reform.ccd.client.model.SearchResult["case_types_results"]) reading POST http://ccd-data-store-api-prod.service.core-compute-prod.internal/searchCases?ctid=GrantOfRepresentation Unrecognized field "case_types_results" (class uk.gov.hmcts.reform.ccd.client.model.SearchResult), not marked as ignorable …
```

19.1.1 release hot fix - temporarily removing 'case_type_results'

---

build.gradle

https://tools.hmcts.net/jira/browse/RDM-10616
Bumped befta-fw version to 6.3.0
```
[ ] Yes
[x] No
```

RDM-10616: Bump befta-fw version to 6.3.0

---

build.gradle

[RDM-10705](https://tools.hmcts.net/jira/browse/RDM-10705) _"Data-store FTA 403 failures when running against a local ccd-docker environment"_
Point to new release version of befta-fw.
```
[ ] Yes
[x] No
```

RDM-10705 - Point to 6.5.3 befta-fw version

---

src/main/java/uk/gov/hmcts/ccd/data/casedetails/CachedCaseDetailsRepository.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseDetailsRepository.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepository.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilder.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilderFactory.java
src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/SelectCaseDetailsReferenceQueryBuilder.java
src/main/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperation.java
src/test/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilderFactoryTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperationTest.java

https://tools.hmcts.net/jira/browse/RDM-11005
Refactor query so we do not fetch whole CaseDetails objects for listing cases accessible by a user
```
[ ] Yes
[X] No
```

RDM-11005: Refactor query so we do not fetch whole CaseDetails object

---

src/main/java/uk/gov/hmcts/ccd/domain/service/search/CaseSearchResultViewGenerator.java
src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/CaseSearchResultViewGeneratorTest.java
src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UICaseSearchControllerIT.java

https://tools.hmcts.net/jira/browse/RDM-11850
```
[ ] Yes
[ X] No
```

RDM-11850: [CASE REFERENCE] metadata field type still returned as 'Number' and not as a String via ES api

---

build.gradle

https://tools.hmcts.net/jira/browse/RDM-12143
bump up dependencies to resolve CVE-2021-29425
```
[ ] Yes
[X] No
```

RDM-12143 CVE-2021-29425 - bump up dependencies to resolve CVE

---

dependency-check-suppressions.xml

CCD-1322 (https://tools.hmcts.net/jira/browse/CCD-1322)
Updated CVE suppression dates in dependency-check-suppressions.xml to 25/07/2021
```
[ ] Yes
[x] No
```

CCD-1322: Updated CVE suppression dates to 25/07/2021

---

src/aat/resources/features/F-032/F-032_Case_Creation_Data_With_Document.td.json
src/aat/resources/features/F-037/S-577.td.json
src/aat/resources/features/F-1001/F-1001-Base-Root.td.json
src/aat/resources/features/F-1002 - Case Update With Documents/S-1011.td.json
src/aat/resources/features/F-1002 - Case Update With Documents/S-1013.td.json
src/aat/resources/features/F-1002 - Case Update With Documents/S-1014.td.json
src/aat/resources/features/F-1002 - Case Update With Documents/S-1015.td.json
src/aat/resources/features/F-1002 - Case Update With Documents/S-1016.td.json
src/aat/resources/features/F-1002 - Case Update With Documents/S-1017.td.json
src/aat/resources/features/F-1002 - Case Update With Documents/S-1018.td.json
src/aat/resources/features/F-1003 - Case Creation With Documents/F-1003-Base-Root.td.json
src/aat/resources/features/F-1003 - Case Creation With Documents/S-1031.td.json
src/aat/resources/features/F-1003 - Case Creation With Documents/S-1034.td.json
src/aat/resources/features/F-1003 - Case Creation With Documents/S-1035.td.json
src/aat/resources/features/F-1003 - Case Creation With Documents/S-1036.td.json
src/aat/resources/features/F-1003 - Case Creation With Documents/S-1037.td.json
src/aat/resources/features/common/case/befta-jurisdiction2-citizen-case-creation/Befta_Jurisdiction2_Default_Citizen_Case_Creation_Data.td.json
src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentUtils.java
src/test/resources/tests/A-case-detail-after-update.json
src/test/resources/tests/A-case-detail-update.json
src/test/resources/tests/SubmitTransactionBadDocumentUpload.json
src/test/resources/tests/SubmitTransactionDocumentUpload.json
src/test/resources/tests/case-detail-after-update.json
src/test/resources/tests/case-detail-before.json
src/test/resources/tests/case-detail-plain-fields-update.json
src/test/resources/tests/new-document-with-hashtoken.json

Addressed TODO in CaseDocumentUtils.java  : Renamed case data document json field hasToken to "document_hash". 
https://tools.hmcts.net/confluence/display/EUI/Expert+UI+-+Feature+Design+-+Secure+docstore
```
[ ] Yes
[ ] No
```

RDM-11352 - renamed case data doc json hasToken to "document_hash"

---

src/aat/resources/features/F-1001/S-1052.td.json
src/aat/resources/features/F-1001/S-1053.td.json
src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/GetCaseDocumentOperation.java
src/main/java/uk/gov/hmcts/ccd/v2/external/controller/CaseDocumentController.java
src/test/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/GetCaseDocumentsOperationTest.java
src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerEventsIT.java
src/test/resources/tests/case-details-data.json

This PR re-implemented  logic to find out case document access for the invoked user. API retrieves the case data and applies standard case access control based on the user details passed in the Authorization header token. It then traverses the case to build a list of the documents which have passed access control.
https://tools.hmcts.net/jira/browse/RDM-12659
```
[ ] Yes
[ ] No
```

RDM-12659 - Checking document id is accessible to user

---

src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseViewOperation.java
src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseViewOperationTest.java

https://tools.hmcts.net/jira/browse/RDM-12575
Adds FieldTypeDefinitions to the CaseViewFields representing accessGranted and accessProcess metadata added to a case view when attribute-based-access-control is enabled
```
[ ] Yes
[X] No
```

RDM-12575 - add FieldTypeDefinitions to CaseView fields

---

src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
src/main/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/CachedRoleAssignmentRepository.java
src/main/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/DefaultRoleAssignmentRepository.java
src/main/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/MultipleQueryRequestResource.java
src/main/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/RoleAssignmentQuery.java
src/main/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/RoleAssignmentRepository.java
src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/RoleAssignmentsDeleteRequest.java
src/main/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperation.java
src/main/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleAssignmentService.java
src/test/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/CachedRoleAssignmentRepositoryTest.java
src/test/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/DefaultRoleAssignmentRepositoryIT.java
src/test/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperationTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleAssignmentServiceTest.java
src/test/resources/mappings/roleassignmentservice/delete_role_assignments_by_query.json

[RDM-10918](https://tools.hmcts.net/jira/browse/RDM-10918) _"Migrate Revoke Access APIs to new Access Control."_
Migrate the following revoke case-role APIs across to to new Access Control (Role Assignment Service)
*  Revoke Access V1, see [F-046](https://github.com/hmcts/ccd-data-store-api/blob/master/src/aat/resources/features/F-046%20-%20Revoke%20Access%20V1/F-046.feature)
* Remove Case-Assigned Users and Roles, see [F-111](https://github.com/hmcts/ccd-data-store-api/blob/master/src/aat/resources/features/F-111%20-%20Remove%20Case-Assigned%20Users%20and%20Roles/F-111.feature)
> NB: This PR is currently based of PR #1555 as there are a number of shared changes between the _"Remove Case-Assigned Users and Roles"_ processing and the _"Add Case-Assigned Users and Roles"_ migrated in …

RDM-10918: Migrate Revoke Access APIs to new Access Control

---

src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/CrossCaseTypeSearchRequest.java
src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/CaseSearchRequestSecurity.java
src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/ElasticsearchCaseSearchRequestSecurity.java
src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/ElasticsearchCaseSearchRequestSecurityTest.java

https://tools.hmcts.net/jira/browse/RDM-12768
This will add in the pre security filters with a new elastic search query to allow multiple case types
```
[ ] Yes
[x] No
```

Rdm 12768 - Implement pre security filters for Global Search endpoint

---

build.gradle
dependency-check-suppressions.xml

CCD-2112 (https://tools.hmcts.net/jira/browse/CCD-2112)
- Updated dependencyManagement section of build.gradle. Set version of org.apache.tomcat.embed group to 9.0.54 to resolve CVE-2021-42340.
- Removed suppression of CVE-2021-42340 from dependency-check-suppressions.xml
```
[ ] Yes
[x] No
```

CCD-2112: Address CVE-2021-42340

---

build.gradle
dependency-check-suppressions.xml

CCD-2136 (https://tools.hmcts.net/jira/browse/CCD-2136)
- Updated build.gradle.  Set value of override of spring-framework.version property to 5.3.12 to address CVE-2021-22096.
- Removed temporary suppression of CVE-2021-22096 from dependency-check-suppressions.xml
```
[ ] Yes
[x] No
```

CCD-2136: Address CVE-2021-22096

---

src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/AuthorisationsMatcher.java
src/main/java/uk/gov/hmcts/ccd/domain/service/AuthorisationMapper.java
src/test/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/AccessProfileServiceImplTest.java
src/test/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/AuthorisationsMatcherTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/DefaultCaseDataAccessControlTest.java

https://tools.hmcts.net/jira/browse/RDM-12965
Cache `RoleToAccessProfiles` info for case types in each request.
```
[ ] Yes
[x] No
```

RDM-12965 - Cache RoleToAccessProfiles info for case types

---

dependency-check-suppressions.xml

CCD-2177 (https://tools.hmcts.net/jira/browse/CCD-2177)
- Removed suppression of CVE-2021-27568 from dependency-check-suppressions.xml.  This was fixed in Pull Request 1564 (https://github.com/hmcts/ccd-data-store-api/pull/1564).  Suppression was added in Pull Request 1558 (https://github.com/hmcts/ccd-data-store-api/pull/1558) which was being worked on in parrallel.
- Documented CVE-2020-23171 as a false positive and moved it to the top of the dependency-check-suppressions.xml file so that position is consistent with suppression files in other components.  This change was originally made under CCD-1871 but the associated pull request - Pull Request 1641 (https://github.com/hmcts/ccd-data-store-api/pull/1641) - wasn't merged.  The changes in Pull Request 1641 itself have also been …

CCD-2177: Review CVE suppressions

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-2231
Changed suppression dates from 2021-12-25 to 2022-01-25
```
[ ] Yes
[X] No
```

CCD-2231-update-cve-suppression-dates-dec-2021

---

src/main/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepository.java

[RDM-13070](https://tools.hmcts.net/jira/browse/RDM-13070) _"Remove caching of jurisdictions in Global Search"_
Remove caching of jurisdictions in Global Search until [CCD-913](https://tools.hmcts.net/jira/browse/CCD-913).
```
[ ] Yes
[x] No
```

RDM-13070 Remove caching of jurisdictions in Global Search

---

Jenkinsfile_nightly

CCD-2400 (https://tools.hmcts.net/jira/browse/CCD-2400)
Updated Jenkinsfile_nightly.  Changed pipeline trigger hour to 04 so as not to conflict with ccd-definition-store-api nightly build.  Believe that conflict with test data used by ccd-definition-store-api tests is causing ccd-data-store-api tests to fail.
```
[ ] Yes
[x] No
```

CCD-2400: Reschedule nightly build

---

src/aat/resources/features/F-1005 - GlobalSearch - Search cases/F-1005.feature
src/main/java/uk/gov/hmcts/ccd/domain/service/search/global/GlobalSearchResponseTransformer.java
src/test/java/uk/gov/hmcts/ccd/domain/service/search/global/GlobalSearchResponseTransformerTest.java

[RDM-13087](https://tools.hmcts.net/jira/browse/RDM-13087) _"Remove GlobalSearch endpoint dependency on Jurisdiction Details call"_
Remove GlobalSearch endpoint dependency on Jurisdiction Details call.
```
[ ] Yes
[x] No
```

RDM-13087 Remove GlobalSearch endpoint dependency on Jurisdiction Details call

---

src/contractTest/resources/application.properties
src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
src/main/java/uk/gov/hmcts/ccd/security/idam/IdamRepository.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/ccd/integrations/IdamRepositoryCachingIT.java
src/test/resources/test.properties

CCD-2539 (https://tools.hmcts.net/jira/browse/CCD-2539)
Added Cacheable annotation to IdamRepository getDataStoreSystemUserAccessToken().  This caches the system user access token and reduces the number of calls made to IDAM.
```
[ ] Yes
[x] No
```

CCD-2539: Cache system user token

---

build.gradle

N/A
Re-added ignoreExitValue property to fortifyScan task in build.gradle.  This was accidentally removed by a previous commit.
```
[ ] Yes
[x] No
```

Re-add ignoreExitValue property to fortifyScan task

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-2893
A security hole was found in the jdbc driver for postgresql database while doing security research
```
[ ] Yes
[x ] No
```

CCD-2893:CVE-2022-21724 - ccd-data-store-api

---

src/main/java/uk/gov/hmcts/ccd/data/caselinking/CaseLinkRepository.java
src/main/java/uk/gov/hmcts/ccd/domain/model/caselinking/CaseLink.java
src/main/java/uk/gov/hmcts/ccd/domain/model/caselinking/CaseLinkDetails.java
src/main/java/uk/gov/hmcts/ccd/domain/model/caselinking/CaseLinksResource.java
src/main/java/uk/gov/hmcts/ccd/domain/model/caselinking/Reason.java
src/main/java/uk/gov/hmcts/ccd/domain/service/caselinking/CaseLinkRetrievalService.java
src/main/java/uk/gov/hmcts/ccd/domain/service/caselinking/GetLinkedCasesResponseCreator.java
src/main/java/uk/gov/hmcts/ccd/v2/external/controller/CaseController.java
src/test/java/uk/gov/hmcts/ccd/data/caselinking/CaseLinkRepositoryTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/caselinking/CaseLinkExtractorTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/caselinking/CaseLinkRetrievalServiceTest.java
src/test/java/uk/gov/hmcts/ccd/domain/service/caselinking/CaseLinkTestFixtures.java
src/test/java/uk/gov/hmcts/ccd/domain/service/caselinking/GetLinkedCasesResponseCreatorTest.java
src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerTest.java
src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerTestIT.java
src/test/resources/mappings/bookcase-definition-caselinks.json
src/test/resources/mappings/jurisdiction_probate.json
src/test/resources/mappings/jurisdictions.json
src/test/resources/sql/insert_cases_get_case_links.sql

[RDM-13139](https://tools.hmcts.net/jira/browse/RDM-13139) _"getLinkedCases API - retrieve case links from database and return response payload"_
Refactor how getLinkedCase API populates its response.
```
[ ] Yes
[x] No
```

Rdm 13139 (PATCH) Refactor how getLinkedCase API populates its response.

---

dependency-check-suppressions.xml

The package com.google.code.gson:gson before 2.8.9 are vulnerable to Deserialization of Untrusted Data via the writeReplace() method in internal classes, which may lead to DoS attacks.
CWE-502 Deserialization of Untrusted Data.
```
[ ] Yes
[ x] No
```

CVE-2022-25647: suppression change

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3098
Upgrading framework to 5.3.20 due to this vulnerability:
In Spring Framework versions 5.3.0 - 5.3.18, 5.2.0 - 5.2.20, and older unsupported versions, the patterns for disallowedFields on a DataBinder are case sensitive which means a field is not effectively protected unless it is listed with both upper and lower case for the first character of the field, including upper and lower case for the first character of all nested fields within the property path.
```
[ ] Yes
[x ] No
```

CCD-3098: CVE-2022-22968: ccd-data-store-api

---

dependency-check-suppressions.xml

CCD-3602 (https://tools.hmcts.net/jira/browse/CCD-3602)
Updated dependency-check-suppressions.xml to temporarily suppress CVE-2022-31197
```
[ ] Yes
[x] No
```

CCD-3602: Temporarily suppress CVE-2022-31197

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3602
Postgres library upgrade for CVE-2022-31197
```
[ ] Yes
[ x] No
```

CCD-3602 Postgres library upgrade

---

src/main/java/uk/gov/hmcts/ccd/domain/service/globalsearch/GlobalSearchParser.java
src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/mapper/CaseDetailsMapper.java
src/test/java/uk/gov/hmcts/ccd/domain/service/globalsearch/GlobalSearchParserTest.java

https://tools.hmcts.net/jira/browse/CCD-3630
Take access profiles into account with Global Search post-filtering
> NB: ES test PRs are:
> * hmcts/ccd-data-store-api#2081
> * hmcts/ccd-definition-store-api#1274
>
> **Both PRs above should be closed once this PR is merged**
```
[ ] Yes
[x] No
```

CCD-3630 - Take access profiles into account with Global Search post-filtering

---

build.gradle
dependency-check-suppressions.xml

Reverts hmcts/ccd-data-store-api#2087
created because failed FTs in master build

Revert "CCD-3436 CVE-2022-34305 tomcat upgrade 9.0.65, suppression removed"

---

dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/ccd/domain/service/casefileview/CategoriesAndDocumentsService.java
src/test/java/uk/gov/hmcts/ccd/domain/service/casefileview/CategoriesAndDocumentsServiceTest.java

https://tools.hmcts.net/jira/browse/CCD-4128
Transform document node containing null caseData to null.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

CCD-4128: NullPointerException on calling getCategoriesAndDocuments

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4233
CVE-2022-45143 Upgrade Tomcat to 9.0.69, suppression removed
```
[ ] Yes
[x ] No
```

CCD-4233 CVE-2022-45143 Upgrade Tomcat to 9.0.69, suppression removed

---

build.gradle
charts/ccd-data-store-api/Chart.yaml
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4398
Upgrade tomcat and commons-fileupload  to resolve CVE-2023-24998
```
[ ] Yes
[ x] No
```

CCD-4398 Upgrade dependencies to resolve CVE-2023-24998

---

.github/workflows/publish-swagger-specs.yml
.travis.yml
README.md
src/aat/resources/features/F-125 - Swagger Pages and API Specs/F-125_Swagger_JSON.td.json

https://tools.hmcts.net/jira/browse/CCD-4476
CCD-4476 : replace reform-api-docs with cnp-api-docs
```
[ ] Yes
[X] No
```

CCD-4476 : replace reform-api-docs with cnp-api-docs

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4739
CCD-4739 : Fix CVE-2023-20863 (bumped versions for springframework and springsecurity)
```
[ ] Yes
[X] No
```

CCD-4739 : Fix CVE-2023-20863 (bumped versions for springframework and springsecurity)

---

build.gradle

https://tools.hmcts.net/jira/browse/DFR-2413
Pact verification results are not being published on the Pact Broker due to incorrect configuration in build.gradle.
```
[ ] Yes
[x] No
```

Fix Pact verification publishing

---

src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/caseassigned/CaseAssignedUserRolesProviderTest.java

https://tools.hmcts.net/jira/browse/DFR-2413
Update ccdDataStoreAPI_caseAssignedUserRoles so that it works for Pact contracts that test /case-users/search
See https://pact-broker.platform.hmcts.net/pacts/provider/ccdDataStoreAPI_caseAssignedUserRoles/consumer/fr_caseOrchestratorService/latest#a_Request_to_search_user_roles_given_A_User_Role_exists_for_a_Case
```
[ ] Yes
[x] No
```

Fix ccdDataStoreAPI_caseAssignedUserRoles Pact

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4972
Fix CVE-2023-41080 : Update org.apache.tomcat.embed to 9.0.82
```
[ ] Yes
[ x] No
```

Fix CVE-2023-41080 : Update org.apache.tomcat.embed to 9.0.82

---

src/main/java/uk/gov/hmcts/ccd/domain/service/casefileview/CategoriesAndDocumentsService.java
src/main/java/uk/gov/hmcts/ccd/domain/types/DateTimeValidator.java
src/test/java/uk/gov/hmcts/ccd/domain/service/casefileview/CategoriesAndDocumentsServiceTest.java

https://tools.hmcts.net/jira/browse/CCD-5408
Use same formatter for CFV as used by the `DateTimeValidator` to ensure any values created can be read by CFV.
```
[ ] Yes
[x] No
```

CCD-5408 - Use same `DateTimeValidator` formatter with CFV

---

Jenkinsfile_CNP

Reference to the branch 'DO-NOT-MERGE-FT-TIMEOUT-EXTENSION' within cnp-jenkins-library repo that extends the ft timeout from 40 to 60 minutes. 
https://github.com/hmcts/cnp-jenkins-library/pull/1229

Reference to the ft timeout extension branch
